"""Fail-closed SSH/SFTP deployment and all-host security generation rollout.

The module accepts already-created role-scoped security bundles.  It neither
creates an SROS2 authority nor persists private material in connection state.
Remote lifecycle behavior is injected because container hosts and the native
Robot service have deliberately different start/stop implementations.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import os
import shlex
import socket
import stat
import subprocess
import tempfile
import uuid
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Callable, Protocol

from .connection_manager import (
    ConnectionTopology,
    ManagedHost,
    SshEndpoint,
    resolve_ssh_identity_path,
)
from .credentials import tailscale_proxy_command


MAX_BUNDLE_FILES = 256
MAX_BUNDLE_FILE_BYTES = 1024 * 1024
MAX_BUNDLE_BYTES = 8 * 1024 * 1024
MAX_REMOTE_OUTPUT_BYTES = 64 * 1024
ProgressCallback = Callable[[str, str | None], None]
_PRIVATE_AUTHORITY_FILES = frozenset(
    {"ca.key.pem", "identity_ca.key.pem", "permissions_ca.key.pem"}
)


class HostKeyVerificationError(RuntimeError):
    """The live SSH host key did not match the operator-pinned fingerprint."""


class SshAuthenticationError(RuntimeError):
    """The selected SSH authentication method was not accepted by the host."""


class SshConnectionError(RuntimeError):
    """The manager could not reach an SSH endpoint before authentication."""


class RemoteCommandError(RuntimeError):
    def __init__(self, argv: Sequence[str], result: "RemoteCommandResult") -> None:
        super().__init__(
            f"remote command failed ({result.exit_status}): "
            f"{shlex.join([str(value) for value in argv])}: {result.stderr.strip()}"
        )
        self.argv = tuple(str(value) for value in argv)
        self.result = result


class RolloutError(RuntimeError):
    def __init__(
        self,
        phase: str,
        cause: BaseException,
        rollback_errors: Sequence[BaseException] = (),
    ) -> None:
        detail = ""
        if rollback_errors:
            detail = f"; rollback also had {len(rollback_errors)} error(s)"
        super().__init__(f"security rollout failed during {phase}: {cause}{detail}")
        self.phase = phase
        self.cause = cause
        self.rollback_errors = tuple(rollback_errors)


@dataclass(frozen=True)
class SecurityFile:
    relative_path: str
    content: bytes
    mode: int = 0o600

    def validate(self) -> "SecurityFile":
        path = _safe_relative_path(self.relative_path)
        if path.name == "manifest.json":
            raise ValueError("manifest.json is generated by the deployment layer")
        if path.name.casefold() in _PRIVATE_AUTHORITY_FILES:
            raise ValueError(f"authority private key must not enter a host bundle: {path}")
        lowered = tuple(part.casefold() for part in path.parts)
        if "authority" in lowered and "private" in lowered:
            raise ValueError(f"authority private material must not enter a host bundle: {path}")
        if not isinstance(self.content, bytes):
            raise ValueError("security file content must be bytes")
        if len(self.content) > MAX_BUNDLE_FILE_BYTES:
            raise ValueError(f"security file is too large: {path}")
        if self.mode not in {0o600, 0o644}:
            raise ValueError("security file mode must be 0600 or 0644")
        return self


@dataclass(frozen=True)
class SecurityBundle:
    system_id: str
    host_id: str
    generation: str
    files: tuple[SecurityFile, ...]

    def validate(self) -> "SecurityBundle":
        _safe_identifier(self.system_id, name="system_id")
        _safe_identifier(self.host_id, name="host_id")
        _safe_generation(self.generation)
        if not self.files or len(self.files) > MAX_BUNDLE_FILES:
            raise ValueError(f"security bundle must contain 1..{MAX_BUNDLE_FILES} files")
        validated = tuple(file.validate() for file in self.files)
        names = [file.relative_path for file in validated]
        if len(set(names)) != len(names):
            raise ValueError("security bundle paths must be unique")
        if sum(len(file.content) for file in validated) > MAX_BUNDLE_BYTES:
            raise ValueError("security bundle exceeds the total byte limit")
        return self

    def manifest(self) -> dict[str, Any]:
        self.validate()
        return {
            "schema_version": 1,
            "system_id": self.system_id,
            "host_id": self.host_id,
            "generation": self.generation,
            "files": [
                {
                    "path": file.relative_path,
                    "size": len(file.content),
                    "mode": f"{file.mode:04o}",
                    "sha256": hashlib.sha256(file.content).hexdigest(),
                }
                for file in sorted(self.files, key=lambda item: item.relative_path)
            ],
        }

    def manifest_bytes(self) -> bytes:
        return (
            json.dumps(self.manifest(), ensure_ascii=False, sort_keys=True, indent=2) + "\n"
        ).encode("utf-8")

    @classmethod
    def from_directory(
        cls,
        *,
        system_id: str,
        host_id: str,
        generation: str,
        root: Path,
    ) -> "SecurityBundle":
        """Load one already-verified authority export into a bounded bundle."""

        candidate = root.expanduser()
        if candidate.is_symlink():
            raise ValueError(f"security bundle root must not be a symlink: {candidate}")
        source = candidate.resolve()
        if not source.is_dir():
            raise ValueError(f"security bundle root is not a directory: {source}")
        files: list[SecurityFile] = []
        for path in sorted(source.rglob("*")):
            if path.is_symlink():
                raise ValueError(f"security bundle must not contain symlinks: {path}")
            if path.is_dir():
                continue
            if not path.is_file():
                raise ValueError(f"security bundle contains a non-regular file: {path}")
            relative = path.relative_to(source).as_posix()
            # The transport produces a fresh digest manifest after upload.
            # The authority manifest must be verified before this adapter runs.
            if relative == "manifest.json":
                continue
            if path.stat().st_size > MAX_BUNDLE_FILE_BYTES:
                raise ValueError(f"security bundle file is too large: {path}")
            source_mode = stat.S_IMODE(path.stat().st_mode)
            mode = 0o644 if source_mode == 0o644 else 0o600
            files.append(SecurityFile(relative, path.read_bytes(), mode))
        return cls(system_id, host_id, generation, tuple(files)).validate()


@dataclass(frozen=True)
class RemoteCommandResult:
    exit_status: int
    stdout: str = ""
    stderr: str = ""


@dataclass(frozen=True)
class RemoteCapabilities:
    docker: bool
    systemd: bool
    jetson: bool
    security_root_writable: bool
    architecture: str = ""

    def require_for(self, host: ManagedHost) -> None:
        if not self.security_root_writable:
            raise RuntimeError(f"host {host.host_id!r} cannot write its security root")
        if host.install_mode == "container" and not self.docker:
            raise RuntimeError(f"host {host.host_id!r} requires Docker")
        if "robot" in host.roles and (not self.jetson or not self.systemd):
            raise RuntimeError(
                f"Robot host {host.host_id!r} requires Jetson and systemd capabilities"
            )


@dataclass(frozen=True)
class HostActivationState:
    """Previous symlink and non-secret install state needed for rollback."""

    generation: str | None
    runtime_configuration: Mapping[str, Any]


class SshSession(Protocol):
    def __enter__(self) -> "SshSession": ...

    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

    def run(
        self, argv: Sequence[str], *, check: bool = True
    ) -> RemoteCommandResult: ...

    def upload_bytes(self, path: PurePosixPath, content: bytes, mode: int) -> None: ...


class SshConnector(Protocol):
    def connect(self, endpoint: SshEndpoint) -> SshSession: ...


class RemoteLifecycle(Protocol):
    """Host-specific runtime operations executed over an authenticated session."""

    def preflight(
        self, session: SshSession, host: ManagedHost, security_root: PurePosixPath
    ) -> RemoteCapabilities: ...

    def snapshot(
        self, session: SshSession, host: ManagedHost
    ) -> Mapping[str, Any]: ...

    def configure(
        self,
        session: SshSession,
        host: ManagedHost,
        generation: str | None,
        security_root: PurePosixPath,
    ) -> None: ...

    def restore(
        self,
        session: SshSession,
        host: ManagedHost,
        configuration: Mapping[str, Any],
    ) -> None: ...

    def stop(self, session: SshSession, host: ManagedHost) -> None: ...

    def start(self, session: SshSession, host: ManagedHost) -> None: ...

    def status(
        self, session: SshSession, host: ManagedHost
    ) -> Mapping[str, Any]: ...

    def verify(
        self, session: SshSession, host: ManagedHost, generation: str | None
    ) -> None: ...


class HostOperations(Protocol):
    def preflight(self, host: ManagedHost) -> RemoteCapabilities: ...

    def capture_state(self, host: ManagedHost) -> HostActivationState: ...

    def stage(self, host: ManagedHost, bundle: SecurityBundle) -> None: ...

    def stop(self, host: ManagedHost) -> None: ...

    def activate(self, host: ManagedHost, generation: str) -> None: ...

    def configure_topology(self, host: ManagedHost) -> None: ...

    def start(self, host: ManagedHost) -> None: ...

    def status(self, host: ManagedHost) -> Mapping[str, Any]: ...

    def verify(self, host: ManagedHost, generation: str) -> None: ...

    def verify_topology(self, host: ManagedHost) -> None: ...

    def rollback(self, host: ManagedHost, previous: HostActivationState) -> None: ...


class ParamikoConnector:
    """Connect with a pinned host key using OpenSSH or Tailscale SSH."""

    def __init__(
        self,
        *,
        timeout_s: float = 10.0,
        command_timeout_s: float = 120.0,
    ) -> None:
        if timeout_s <= 0 or command_timeout_s <= 0:
            raise ValueError("SSH timeouts must be positive")
        self._timeout_s = float(timeout_s)
        self._command_timeout_s = float(command_timeout_s)

    def connect(self, endpoint: SshEndpoint) -> SshSession:
        import paramiko

        endpoint.validate()
        if endpoint.uses_tailscale_ssh:
            return self._connect_tailscale(endpoint, paramiko)
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(
            _PinnedHostKeyPolicy(endpoint.pinned_fingerprint)
        )
        arguments: dict[str, Any] = {
            "hostname": endpoint.host,
            "port": int(endpoint.port),
            "username": endpoint.user,
            "password": None,
            "allow_agent": endpoint.uses_agent,
            "look_for_keys": False,
            "timeout": self._timeout_s,
            "banner_timeout": self._timeout_s,
            "auth_timeout": self._timeout_s,
        }
        if not endpoint.uses_agent:
            arguments["key_filename"] = str(
                resolve_ssh_identity_path(endpoint.identity_file)
            )
        try:
            client.connect(**arguments)
        except BaseException:
            client.close()
            raise
        return _ParamikoSession(
            client,
            command_timeout_s=self._command_timeout_s,
        )

    def _connect_tailscale(self, endpoint: SshEndpoint, paramiko: object) -> SshSession:
        """Authenticate through the Tailscale SSH server without a local key.

        Tailscale SSH presents a normal SSH transport on TCP/22, but accepts
        Tailscale identity rather than an OpenSSH key.  Paramiko's regular
        ``SSHClient.connect`` path never sends the required ``none`` request,
        so establish the transport explicitly and then hand it to the normal
        session wrapper.  The compatibility password fallback is the method
        documented by Tailscale for clients that cannot use ``auth_none``;
        the value is a disposable placeholder, never a stored credential.
        """

        connection: object | None = None
        transport: object | None = None
        try:
            proxy_command = tailscale_proxy_command(
                endpoint.host,
                int(endpoint.port),
                force=True,
            )
            if proxy_command is None:
                connection = socket.create_connection(
                    (endpoint.host, int(endpoint.port)), timeout=self._timeout_s
                )
            else:
                from paramiko.proxy import ProxyCommand

                connection = ProxyCommand(proxy_command)
            transport = paramiko.Transport(connection)  # type: ignore[attr-defined]
            # Paramiko's Transport defaults auth_timeout to None.  Tailscale
            # ``action=check`` can otherwise leave a headless rollout waiting
            # forever while the user has not approved the interactive check.
            transport.auth_timeout = self._timeout_s  # type: ignore[attr-defined]
            transport.start_client(timeout=self._timeout_s)  # type: ignore[attr-defined]
            key = transport.get_remote_server_key()  # type: ignore[attr-defined]
            _verify_pinned_host_key(endpoint, key)
            authenticated = False
            try:
                transport.auth_none(endpoint.user)  # type: ignore[attr-defined]
                authenticated = bool(transport.is_authenticated())  # type: ignore[attr-defined]
            except Exception:
                # Some SSH libraries cannot issue SSH_MSG_USERAUTH_NONE to the
                # Tailscale server.  Tailscale documents ``user+password`` with
                # any password as its compatibility spelling for those clients.
                authenticated = False
            if not authenticated:
                try:
                    transport.auth_password(  # type: ignore[attr-defined]
                        f"{endpoint.user}+password", "tailscale"
                    )
                    authenticated = bool(transport.is_authenticated())  # type: ignore[attr-defined]
                except Exception as exc:
                    raise SshAuthenticationError(
                        f"Tailscale SSH authentication failed for "
                        f"{endpoint.user}@{endpoint.host}. "
                        "If the ACL uses action=check, approve one interactive "
                        "Tailscale SSH re-authentication first and verify that "
                        "the ACL permits this user. Tailscale SSH uses port 22 "
                        "and does not use a private-key path."
                    ) from exc
            if not authenticated:
                raise SshAuthenticationError(
                    f"Tailscale SSH did not authenticate {endpoint.user}@{endpoint.host}. "
                    "If the ACL uses action=check, approve one interactive "
                    "Tailscale SSH re-authentication first and verify the ACL user."
                )
            client = paramiko.SSHClient()  # type: ignore[attr-defined]
            # SSHClient owns and closes this transport through its normal close
            # path.  This is the only private Paramiko attribute we rely on;
            # it has been stable since Paramiko's Transport split.
            client._transport = transport  # type: ignore[attr-defined]
            transport = None
            return _ParamikoSession(
                client,
                command_timeout_s=self._command_timeout_s,
            )
        except (HostKeyVerificationError, SshAuthenticationError):
            raise
        except (TimeoutError, socket.timeout) as exc:
            raise SshConnectionError(
                f"SSH connection to {endpoint.host}:{endpoint.port} timed out. "
                "Check the remote SSH service, Tailscale SSH/ACL, and the "
                "connection-manager network path."
            ) from exc
        except OSError as exc:
            detail = str(exc).strip() or exc.__class__.__name__
            raise SshConnectionError(
                f"SSH connection to {endpoint.host}:{endpoint.port} failed: {detail}. "
                "Check the remote SSH service, Tailscale SSH/ACL, and the "
                "connection-manager network path."
            ) from exc
        finally:
            if transport is not None:
                transport.close()  # type: ignore[attr-defined]
            elif connection is not None:
                # Transport owns the socket after a successful hand-off.  On a
                # failed socket/transport construction, close the raw socket.
                try:
                    connection.close()  # type: ignore[attr-defined]
                except BaseException:
                    pass


class _PinnedHostKeyPolicy:
    def __init__(self, expected: str) -> None:
        self._expected = expected

    def missing_host_key(self, _client: object, hostname: str, key: object) -> None:
        _verify_pinned_host_key_values(hostname, key, self._expected)


def _verify_pinned_host_key(endpoint: SshEndpoint, key: object) -> None:
    _verify_pinned_host_key_values(endpoint.host, key, endpoint.pinned_fingerprint)


def _verify_pinned_host_key_values(hostname: str, key: object, expected: str) -> None:
    try:
        key_bytes = key.asbytes()  # type: ignore[attr-defined]
    except (AttributeError, TypeError) as exc:
        raise HostKeyVerificationError(
            f"SSH server {hostname!r} supplied an invalid host key"
        ) from exc
    actual = ssh_sha256_fingerprint(key_bytes)
    if not hmac.compare_digest(actual, expected):
        raise HostKeyVerificationError(
            f"SSH host-key mismatch for {hostname!r}: expected "
            f"{expected}, received {actual}"
        )


class _ParamikoSession:
    def __init__(self, client: object, *, command_timeout_s: float) -> None:
        self._client = client
        self._command_timeout_s = float(command_timeout_s)
        self._sftp: object | None = None

    def __enter__(self) -> "_ParamikoSession":
        return self

    def __exit__(self, _exc_type: object, _exc: object, _traceback: object) -> None:
        if self._sftp is not None:
            self._sftp.close()  # type: ignore[attr-defined]
        self._client.close()  # type: ignore[attr-defined]

    def run(
        self, argv: Sequence[str], *, check: bool = True
    ) -> RemoteCommandResult:
        if not argv or any("\x00" in str(value) for value in argv):
            raise ValueError("remote command argv must be non-empty and contain no NUL")
        command = shlex.join([str(value) for value in argv])
        _stdin, stdout, stderr = self._client.exec_command(  # type: ignore[attr-defined]
            command,
            timeout=self._command_timeout_s,
        )
        stdout_raw = stdout.read(MAX_REMOTE_OUTPUT_BYTES + 1)
        stderr_raw = stderr.read(MAX_REMOTE_OUTPUT_BYTES + 1)
        if len(stdout_raw) > MAX_REMOTE_OUTPUT_BYTES or len(stderr_raw) > MAX_REMOTE_OUTPUT_BYTES:
            raise RemoteCommandError(
                tuple(argv),
                RemoteCommandResult(1, stderr="remote command output exceeded limit"),
            )
        result = RemoteCommandResult(
            exit_status=int(stdout.channel.recv_exit_status()),
            stdout=stdout_raw.decode("utf-8", errors="replace"),
            stderr=stderr_raw.decode("utf-8", errors="replace"),
        )
        if check and result.exit_status != 0:
            raise RemoteCommandError(argv, result)
        return result

    def upload_bytes(self, path: PurePosixPath, content: bytes, mode: int) -> None:
        if not path.is_absolute() or ".." in path.parts:
            raise ValueError("remote upload path must be absolute and contained")
        if len(content) > MAX_BUNDLE_FILE_BYTES:
            raise ValueError("remote upload exceeds per-file limit")
        sftp = self._get_sftp()
        _sftp_makedirs(sftp, path.parent)
        with sftp.file(str(path), "wb") as handle:  # type: ignore[attr-defined]
            handle.write(content)
            handle.flush()
        sftp.chmod(str(path), mode)  # type: ignore[attr-defined]

    def _get_sftp(self) -> object:
        if self._sftp is None:
            self._sftp = self._client.open_sftp()  # type: ignore[attr-defined]
            self._sftp.get_channel().settimeout(  # type: ignore[attr-defined]
                self._command_timeout_s
            )
        return self._sftp


class SshHostOperations:
    """Deploy one host bundle through a role-specific remote lifecycle."""

    def __init__(
        self,
        connector: SshConnector,
        lifecycle: RemoteLifecycle,
        topology: ConnectionTopology,
        *,
        security_root: str | None = None,
    ) -> None:
        self._connector = connector
        self._lifecycle = lifecycle
        self._topology = topology.validate()
        self._security_root_override = (
            None if security_root is None else _safe_remote_root(security_root)
        )

    def preflight(self, host: ManagedHost) -> RemoteCapabilities:
        security_root = self._security_root_for(host)
        with self._connect(host) as session:
            return self._lifecycle.preflight(session, host, security_root)

    def capture_state(self, host: ManagedHost) -> HostActivationState:
        security_root = self._security_root_for(host)
        with self._connect(host) as session:
            result = session.run(
                ("readlink", str(security_root / "current")), check=False
            )
            configuration = dict(self._lifecycle.snapshot(session, host))
        generation: str | None = None
        if result.exit_status == 0 and result.stdout.strip():
            generation = PurePosixPath(result.stdout.strip()).name
            _safe_generation(generation)
        return HostActivationState(generation, configuration)

    def stage(self, host: ManagedHost, bundle: SecurityBundle) -> None:
        _check_bundle_target(host, bundle)
        security_root = self._security_root_for(host)
        generation_root = security_root / "generations"
        final_root = generation_root / bundle.generation
        stage_root = security_root / ".staging" / (
            f"{bundle.generation}-{uuid.uuid4().hex}"
        )
        with self._connect(host) as session:
            session.run(("mkdir", "-p", str(generation_root), str(stage_root.parent)))
            exists = session.run(("test", "-e", str(final_root)), check=False)
            symlink = session.run(("test", "-L", str(final_root)), check=False)
            if exists.exit_status == 0 or symlink.exit_status == 0:
                raise FileExistsError(
                    f"security generation already exists on {host.host_id}: "
                    f"{bundle.generation}"
                )
            session.run(("mkdir", str(stage_root)))
            session.run(("chmod", "0700", str(stage_root)))
            try:
                for file in sorted(bundle.files, key=lambda item: item.relative_path):
                    file.validate()
                    session.upload_bytes(
                        stage_root / PurePosixPath(file.relative_path),
                        file.content,
                        file.mode,
                    )
                session.upload_bytes(
                    stage_root / "manifest.json", bundle.manifest_bytes(), 0o600
                )
                session.run(("mv", str(stage_root), str(final_root)))
            except BaseException:
                session.run(("rm", "-rf", "--", str(stage_root)), check=False)
                raise

    def stop(self, host: ManagedHost) -> None:
        with self._connect(host) as session:
            self._lifecycle.stop(session, host)

    def activate(self, host: ManagedHost, generation: str) -> None:
        _safe_generation(generation)
        security_root = self._security_root_for(host)
        final_root = security_root / "generations" / generation
        temporary = security_root / f".current-{uuid.uuid4().hex}"
        current = security_root / "current"
        with self._connect(host) as session:
            session.run(("test", "-d", str(final_root)))
            session.run(("ln", "-s", str(final_root), str(temporary)))
            try:
                session.run(("mv", "-Tf", str(temporary), str(current)))
            except BaseException:
                session.run(("rm", "-f", "--", str(temporary)), check=False)
                raise
            self._sync_role_views(
                session,
                host,
                security_root,
                generation=generation,
            )
            self._lifecycle.configure(session, host, generation, security_root)

    def configure_topology(self, host: ManagedHost) -> None:
        if self._topology.security_profile != "trusted-network":
            raise ValueError(
                "bundle-free topology configuration is limited to trusted-network"
            )
        security_root = self._security_root_for(host)
        with self._connect(host) as session:
            self._lifecycle.configure(session, host, None, security_root)

    def start(self, host: ManagedHost) -> None:
        with self._connect(host) as session:
            self._lifecycle.start(session, host)

    def status(self, host: ManagedHost) -> Mapping[str, Any]:
        with self._connect(host) as session:
            result = dict(self._lifecycle.status(session, host))
        result.setdefault("host_id", host.host_id)
        result.setdefault("roles", list(host.roles))
        return result

    def verify(self, host: ManagedHost, generation: str) -> None:
        _safe_generation(generation)
        with self._connect(host) as session:
            self._lifecycle.verify(session, host, generation)

    def verify_topology(self, host: ManagedHost) -> None:
        with self._connect(host) as session:
            self._lifecycle.verify(session, host, None)

    def rollback(self, host: ManagedHost, previous: HostActivationState) -> None:
        security_root = self._security_root_for(host)
        if previous.generation is not None:
            self._switch_only(host, previous.generation)
        else:
            with self._connect(host) as session:
                session.run(
                    ("rm", "-f", "--", str(security_root / "current")),
                    check=False,
                )
                self._sync_role_views(
                    session,
                    host,
                    security_root,
                    generation=None,
                )
        with self._connect(host) as session:
            self._lifecycle.restore(session, host, previous.runtime_configuration)

    def _switch_only(self, host: ManagedHost, generation: str) -> None:
        _safe_generation(generation)
        security_root = self._security_root_for(host)
        final_root = security_root / "generations" / generation
        temporary = security_root / f".current-{uuid.uuid4().hex}"
        current = security_root / "current"
        with self._connect(host) as session:
            session.run(("test", "-d", str(final_root)))
            session.run(("ln", "-s", str(final_root), str(temporary)))
            try:
                session.run(("mv", "-Tf", str(temporary), str(current)))
            except BaseException:
                session.run(("rm", "-f", "--", str(temporary)), check=False)
                raise
            self._sync_role_views(
                session,
                host,
                security_root,
                generation=generation,
            )

    @staticmethod
    def _sync_role_views(
        session: SshSession,
        host: ManagedHost,
        security_root: PurePosixPath,
        *,
        generation: str | None,
    ) -> None:
        """Refresh stable role roots in place while application services stop."""

        roles_root = security_root / "roles"
        if session.run(("test", "-L", str(roles_root)), check=False).exit_status == 0:
            raise RuntimeError(f"role keystore root is a symlink: {roles_root}")
        session.run(("mkdir", "-p", str(roles_root)))
        session.run(("chmod", "0700", str(roles_root)))

        sources: dict[str, PurePosixPath] = {}
        for role in host.roles:
            destination = roles_root / role
            if session.run(
                ("test", "-L", str(destination)), check=False
            ).exit_status == 0:
                raise RuntimeError(f"role keystore is a symlink: {destination}")
            session.run(("mkdir", "-p", str(destination)))
            session.run(("chmod", "0700", str(destination)))
            for name in ("public", "enclaves"):
                child = destination / name
                if session.run(
                    ("test", "-L", str(child)), check=False
                ).exit_status == 0:
                    raise RuntimeError(f"role keystore child is a symlink: {child}")
            if generation is None:
                continue
            source = (
                security_root
                / "generations"
                / generation
                / "roles"
                / role
                / "keystore"
            )
            session.run(("test", "-d", str(source / "public")))
            session.run(("test", "-d", str(source / "enclaves")))
            sources[role] = source

        for role in host.roles:
            destination = roles_root / role
            session.run(
                (
                    "rm",
                    "-rf",
                    "--",
                    str(destination / "public"),
                    str(destination / "enclaves"),
                )
            )
            source = sources.get(role)
            if source is None:
                continue
            session.run(
                ("cp", "-a", str(source / "public"), str(destination / "public"))
            )
            session.run(
                (
                    "cp",
                    "-a",
                    str(source / "enclaves"),
                    str(destination / "enclaves"),
                )
            )

    def _security_root_for(self, host: ManagedHost) -> PurePosixPath:
        if self._topology.host(host.host_id) != host:
            raise ValueError(f"host {host.host_id!r} does not match the managed topology")
        if self._security_root_override is not None:
            return self._security_root_override
        return _safe_remote_root(str(PurePosixPath(host.install_root) / "security"))

    def _connect(self, host: ManagedHost) -> SshSession:
        if host.local or host.ssh is None:
            raise ValueError(
                f"SshHostOperations cannot operate local host {host.host_id!r}; "
                "inject local HostOperations instead"
            )
        return self._connector.connect(host.ssh)


class LocalHostOperations(SshHostOperations):
    """Apply the same transaction locally without shell interpolation or SSH."""

    def __init__(
        self,
        lifecycle: RemoteLifecycle,
        topology: ConnectionTopology,
        *,
        security_root: str | None = None,
        timeout_s: float = 30.0,
    ) -> None:
        super().__init__(
            _UnavailableConnector(),
            lifecycle,
            topology,
            security_root=security_root,
        )
        if timeout_s <= 0:
            raise ValueError("local command timeout must be positive")
        self._local_timeout_s = float(timeout_s)

    def _connect(self, host: ManagedHost) -> SshSession:
        if not host.local:
            raise ValueError(
                f"LocalHostOperations cannot operate remote host {host.host_id!r}"
            )
        return _LocalSession(timeout_s=self._local_timeout_s)


class _UnavailableConnector:
    def connect(self, _endpoint: SshEndpoint) -> SshSession:
        raise AssertionError("LocalHostOperations must not use an SSH connector")


class _LocalSession:
    def __init__(self, *, timeout_s: float) -> None:
        self._timeout_s = timeout_s

    def __enter__(self) -> "_LocalSession":
        return self

    def __exit__(self, _exc_type: object, _exc: object, _traceback: object) -> None:
        return None

    def run(
        self, argv: Sequence[str], *, check: bool = True
    ) -> RemoteCommandResult:
        values = tuple(str(value) for value in argv)
        if not values or any("\x00" in value for value in values):
            raise ValueError("local command argv must be non-empty and contain no NUL")
        completed = subprocess.run(
            values,
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=self._timeout_s,
        )
        if (
            len(completed.stdout) > MAX_REMOTE_OUTPUT_BYTES
            or len(completed.stderr) > MAX_REMOTE_OUTPUT_BYTES
        ):
            raise RemoteCommandError(
                values,
                RemoteCommandResult(1, stderr="local command output exceeded limit"),
            )
        result = RemoteCommandResult(
            completed.returncode,
            completed.stdout.decode("utf-8", errors="replace"),
            completed.stderr.decode("utf-8", errors="replace"),
        )
        if check and result.exit_status != 0:
            raise RemoteCommandError(values, result)
        return result

    def upload_bytes(self, path: PurePosixPath, content: bytes, mode: int) -> None:
        if not path.is_absolute() or ".." in path.parts:
            raise ValueError("local deployment path must be absolute and contained")
        if len(content) > MAX_BUNDLE_FILE_BYTES:
            raise ValueError("local upload exceeds per-file limit")
        destination = Path(str(path))
        destination.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        descriptor, temporary_name = tempfile.mkstemp(
            dir=destination.parent, prefix=f".{destination.name}."
        )
        temporary = Path(temporary_name)
        try:
            os.fchmod(descriptor, mode)
            with os.fdopen(descriptor, "wb") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary, destination)
            os.chmod(destination, mode)
        finally:
            if temporary.exists():
                temporary.unlink()


class InstalledElesimLifecycle:
    """Concrete lifecycle for fixed Compose hosts and the native Robot service."""

    def __init__(self, topology: ConnectionTopology) -> None:
        self._topology = topology.validate()

    def preflight(
        self, session: SshSession, host: ManagedHost, security_root: PurePosixPath
    ) -> RemoteCapabilities:
        state = self.snapshot(session, host)
        configured_roles = tuple(str(value) for value in state.get("roles", ()))
        if set(configured_roles) != set(host.roles):
            raise RuntimeError(
                f"installed roles on {host.host_id!r} do not match assignments: "
                f"{configured_roles!r} != {host.roles!r}"
            )
        if str(state.get("prefix", "")) != host.install_root:
            raise RuntimeError(f"install_root mismatch on {host.host_id!r}")
        if str(state.get("bin_dir", "")) != host.bin_dir:
            raise RuntimeError(f"bin_dir mismatch on {host.host_id!r}")
        if str(state.get("install_mode", "")) != host.install_mode:
            raise RuntimeError(f"install_mode mismatch on {host.host_id!r}")

        writable = session.run(
            ("test", "-w", str(PurePosixPath(host.install_root))), check=False
        ).exit_status == 0
        docker = session.run(
            ("docker", "version", "--format", "{{.Server.Version}}"), check=False
        ).exit_status == 0
        systemd = session.run(
            ("test", "-x", "/usr/bin/systemctl"), check=False
        ).exit_status == 0
        jetson = session.run(
            ("test", "-f", "/etc/nv_tegra_release"), check=False
        ).exit_status == 0
        architecture_result = session.run(("uname", "-m"), check=False)

        if host.lifecycle == "compose":
            compose = PurePosixPath(host.install_root) / "containers/compose.yaml"
            if session.run(("test", "-f", str(compose)), check=False).exit_status != 0:
                raise RuntimeError(f"Compose manifest is missing on {host.host_id!r}")
        else:
            service = _robot_service(host)
            sudo_probe = session.run(
                (
                    "sudo",
                    "-n",
                    "systemctl",
                    "show",
                    service,
                    "--property=LoadState",
                    "--value",
                ),
                check=False,
            )
            systemd = systemd and sudo_probe.exit_status == 0 and (
                sudo_probe.stdout.strip() == "loaded"
            )

        # The root is deliberately below the user-owned install prefix.  It is
        # created during staging, after every host has passed this read-only probe.
        expected_root = PurePosixPath(host.install_root) / "security"
        if security_root != expected_root:
            writable = writable and session.run(
                ("test", "-w", str(security_root.parent)), check=False
            ).exit_status == 0
        return RemoteCapabilities(
            docker=docker,
            systemd=systemd,
            jetson=jetson,
            security_root_writable=writable,
            architecture=architecture_result.stdout.strip(),
        )

    def snapshot(
        self, session: SshSession, host: ManagedHost
    ) -> Mapping[str, Any]:
        result = session.run((str(_net_command(host)), "show"))
        try:
            raw = json.loads(result.stdout)
        except json.JSONDecodeError as exc:
            raise RuntimeError(
                f"elesim-net show returned invalid JSON on {host.host_id!r}"
            ) from exc
        if not isinstance(raw, Mapping):
            raise RuntimeError(f"installed state is not an object on {host.host_id!r}")
        return dict(raw)

    def configure(
        self,
        session: SshSession,
        host: ManagedHost,
        generation: str | None,
        security_root: PurePosixPath,
    ) -> None:
        values: dict[str, Any] = {
            "system_id": self._topology.system_id,
            "domain_id": self._topology.dds_graph.domain_id,
            "rmw_implementation": self._topology.dds_graph.rmw_implementation,
            "discovery_mode": self._topology.dds_graph.discovery_mode,
            "static_peers": self._topology.discovery_peers(host.host_id),
            "interface": host.dds.interface,
            "security_profile": self._topology.security_profile,
        }
        if self._topology.security_profile == "sros2":
            if generation is None:
                raise ValueError("managed sros2 configuration requires a generation")
            values.update(
                {
                    "security_provisioning": "managed",
                    "security_generation": generation,
                    "security_bundle": str(
                        security_root / "current" / "keystore"
                    ),
                    "keystore": str(security_root / "current" / "keystore"),
                    "enclave": f"/elesim/{self._topology.system_id}",
                }
            )
        else:
            if generation is not None:
                raise ValueError("trusted-network configuration has no generation")
            values.update(
                {
                    "security_provisioning": "none",
                    "security_generation": "",
                    "security_bundle": "",
                    "keystore": "",
                    "enclave": "",
                }
            )
        endpoints = {
            assignment.role: assignment.endpoint_id
            for managed_host in self._topology.hosts
            for assignment in managed_host.assignments
        }
        session.run(
            _configuration_command(
                host,
                values,
                sim_id=endpoints.get("sim", ""),
                pilot_id=endpoints.get("pilot", ""),
                ui_id=endpoints.get("ui", ""),
                robot_id=endpoints.get("robot", ""),
            )
        )

    def restore(
        self,
        session: SshSession,
        host: ManagedHost,
        configuration: Mapping[str, Any],
    ) -> None:
        dds = configuration.get("dds")
        network = configuration.get("network", {})
        if not isinstance(dds, Mapping) or not isinstance(network, Mapping):
            raise RuntimeError(f"rollback state is malformed for {host.host_id!r}")
        session.run(
            _configuration_command(
                host,
                dds,
                sim_id=str(network.get("sim_id", "")),
                pilot_id=str(network.get("pilot_id", "")),
                ui_id=str(network.get("ui_id", "ui-main")),
                # A simulation-only rollback must not resurrect a stale Robot
                # endpoint from an older installed state.  Full topologies
                # retain the historical fallback for backwards-compatible
                # rollback of Robot hosts.
                robot_id=(
                    ""
                    if self._topology.topology_mode == "simulation-only"
                    else str(network.get("robot_id", "robot-go2"))
                ),
            )
        )

    def stop(self, session: SshSession, host: ManagedHost) -> None:
        session.run(_lifecycle_command(host, action="stop"))

    def start(self, session: SshSession, host: ManagedHost) -> None:
        session.run(_lifecycle_command(host, action="start"))

    def status(self, session: SshSession, host: ManagedHost) -> Mapping[str, Any]:
        """Return a bounded lifecycle snapshot without changing host state."""

        if host.lifecycle == "compose":
            result = session.run(
                (*_compose_command(host), "ps", "--status", "running", "--services"),
                check=False,
            )
            expected = set(host.roles)
            # The manager/tools services may also be running in this Compose
            # project, but they are not application roles and must not make a
            # host look degraded before Pilot/Sim/UI have started.
            running = tuple(
                sorted(value for value in result.stdout.split() if value in expected)
            )
            active = expected.issubset(set(running))
            state = "running" if active else ("stopped" if not running else "degraded")
            return {
                "state": state,
                "running_roles": list(running),
                "detail": result.stderr.strip()[:512],
            }
        result = session.run(
            ("sudo", "-n", "systemctl", "is-active", _robot_service(host)),
            check=False,
        )
        value = result.stdout.strip()
        state = value if value in {"active", "inactive", "failed", "unknown"} else "unknown"
        return {
            "state": "running" if state == "active" else state,
            "running_roles": list(host.roles),
            "detail": result.stderr.strip()[:512],
        }

    def verify(
        self, session: SshSession, host: ManagedHost, generation: str | None
    ) -> None:
        if host.lifecycle == "compose":
            result = session.run(
                (*_compose_command(host), "ps", "--status", "running", "--services")
            )
            running = set(result.stdout.split())
            missing = sorted(set(host.roles) - running)
            if missing:
                raise RuntimeError(
                    f"roles are not running on {host.host_id!r}: {', '.join(missing)}"
                )
        else:
            session.run(("sudo", "-n", "systemctl", "is-active", "--quiet", _robot_service(host)))
        state = self.snapshot(session, host)
        dds = state.get("dds")
        if not isinstance(dds, Mapping):
            raise RuntimeError(f"DDS state is missing on {host.host_id!r}")
        expected = {
            "system_id": self._topology.system_id,
            "domain_id": self._topology.dds_graph.domain_id,
            "rmw_implementation": self._topology.dds_graph.rmw_implementation,
            "discovery_mode": self._topology.dds_graph.discovery_mode,
            "static_peers": list(self._topology.discovery_peers(host.host_id)),
            "interface": host.dds.interface,
            "security_profile": self._topology.security_profile,
        }
        for name, value in expected.items():
            actual = dds.get(name)
            if name == "static_peers":
                actual = list(actual or ())
            if actual != value:
                raise RuntimeError(
                    f"DDS {name} did not activate on {host.host_id!r}: "
                    f"{actual!r} != {value!r}"
                )
        if generation is not None and str(dds.get("security_generation", "")) != generation:
            raise RuntimeError(f"security generation did not activate on {host.host_id!r}")
        session.run((str(_net_command(host)), "doctor", "--json"))


@dataclass(frozen=True)
class RolloutResult:
    generation: str
    previous_generations: Mapping[str, str | None]


@dataclass(frozen=True)
class IssuedSecurityGeneration:
    generation: str
    bundles: Mapping[str, SecurityBundle]
    activate_authority: Callable[[], object]
    rollback_authority: Callable[[], object]


class SecurityGenerationIssuer(Protocol):
    def issue(
        self, topology: ConnectionTopology, generation: str
    ) -> IssuedSecurityGeneration: ...


class Sros2BundleIssuer:
    """Issue least-privilege enclaves and adapt verified host exports."""

    def __init__(self, authority: object) -> None:
        # Kept structurally typed so tests can inject the ROS CLI runner through
        # Sros2Authority without duplicating cryptographic code here.
        self._authority = authority

    def issue(
        self, topology: ConnectionTopology, generation: str
    ) -> IssuedSecurityGeneration:
        from .security_authority import verify_bundle
        from .security_policy import write_role_policy

        topology.validate()
        if topology.security_profile != "sros2":
            raise ValueError("SROS2 bundle issuance requires the sros2 profile")
        _safe_generation(generation)
        endpoints = {
            assignment.role: assignment.endpoint_id
            for host in topology.hosts
            for assignment in host.assignments
        }
        transaction = self._authority.begin_generation(  # type: ignore[attr-defined]
            topology.system_id, generation=generation
        )
        with transaction, tempfile.TemporaryDirectory(
            prefix="elesim-sros2-policies-"
        ) as temporary_directory:
            policy_root = Path(temporary_directory)
            identities: dict[str, object] = {}
            for role in sorted(endpoints):
                policy = write_role_policy(
                    policy_root / f"{role}.policy.xml",
                    system_id=topology.system_id,
                    role=role,
                    endpoint_id=endpoints[role],
                    endpoints=endpoints,
                )
                if not policy.is_file():
                    raise RuntimeError(f"role policy was not created: {policy}")
                identities[role] = transaction.create_enclave(
                    role, endpoints[role], policy=policy
                )
            for host in topology.hosts:
                transaction.stage_host_bundle(
                    host.host_id,
                    tuple(identities[assignment.role] for assignment in host.assignments),
                )
            transaction.publish()

        bundles: dict[str, SecurityBundle] = {}
        for host in topology.hosts:
            source = transaction.path / "bundles" / host.host_id
            verify_bundle(source)
            bundles[host.host_id] = SecurityBundle.from_directory(
                system_id=topology.system_id,
                host_id=host.host_id,
                generation=generation,
                root=source,
            )
        return IssuedSecurityGeneration(
            generation=generation,
            bundles=bundles,
            activate_authority=transaction.activate,
            rollback_authority=lambda: _rollback_authority_if_active(
                self._authority, transaction, generation
            ),
        )


@dataclass(frozen=True)
class TopologyRolloutResult:
    previous_generations: Mapping[str, str | None]


class TopologyRollout:
    """Apply a bundle-free trusted-network graph change to every host."""

    def __init__(
        self,
        topology: ConnectionTopology,
        operations: Mapping[str, HostOperations],
    ) -> None:
        self._topology = topology.validate()
        if self._topology.security_profile != "trusted-network":
            raise ValueError("TopologyRollout is for trusted-network only")
        host_ids = {host.host_id for host in self._topology.hosts}
        if set(operations) != host_ids:
            raise ValueError("HostOperations must be supplied exactly once for every host")
        self._operations = dict(operations)

    def apply(
        self, *, progress: ProgressCallback | None = None
    ) -> TopologyRolloutResult:
        hosts = self._topology.hosts
        previous: dict[str, HostActivationState] = {}
        stopped: list[ManagedHost] = []
        configured: list[ManagedHost] = []
        phase = "preflight"
        try:
            for host in hosts:
                _notify_progress(progress, phase, host.host_id)
                capabilities = self._operations[host.host_id].preflight(host)
                capabilities.require_for(host)
            phase = "capture-current-state"
            for host in hosts:
                _notify_progress(progress, phase, host.host_id)
                previous[host.host_id] = self._operations[
                    host.host_id
                ].capture_state(host)
            phase = "stop"
            for host in hosts:
                _notify_progress(progress, phase, host.host_id)
                stopped.append(host)
                self._operations[host.host_id].stop(host)
            phase = "configure"
            for host in hosts:
                _notify_progress(progress, phase, host.host_id)
                configured.append(host)
                self._operations[host.host_id].configure_topology(host)
            phase = "start"
            for host in hosts:
                _notify_progress(progress, phase, host.host_id)
                self._operations[host.host_id].start(host)
            phase = "verify"
            for host in hosts:
                _notify_progress(progress, phase, host.host_id)
                self._operations[host.host_id].verify_topology(host)
        except BaseException as exc:
            rollback_errors = _restore_hosts(
                self._operations,
                stopped=stopped,
                changed=configured,
                previous=previous,
            )
            raise RolloutError(phase, exc, rollback_errors) from exc
        return TopologyRolloutResult(
            {host_id: state.generation for host_id, state in previous.items()}
        )


class GenerationRollout:
    """Perform an all-host generation transition without a mixed live graph."""

    def __init__(
        self,
        topology: ConnectionTopology,
        operations: Mapping[str, HostOperations],
    ) -> None:
        self._topology = topology.validate()
        host_ids = {host.host_id for host in self._topology.hosts}
        if set(operations) != host_ids:
            raise ValueError("HostOperations must be supplied exactly once for every host")
        self._operations = dict(operations)

    def _prepare_hosts(
        self,
        *,
        progress: ProgressCallback | None = None,
    ) -> dict[str, HostActivationState]:
        """Validate every host before any new security generation is issued."""

        previous: dict[str, HostActivationState] = {}
        phase = "preflight"
        try:
            for host in self._topology.hosts:
                _notify_progress(progress, phase, host.host_id)
                capabilities = self._operations[host.host_id].preflight(host)
                capabilities.require_for(host)
            phase = "capture-current-state"
            for host in self._topology.hosts:
                _notify_progress(progress, phase, host.host_id)
                previous[host.host_id] = self._operations[
                    host.host_id
                ].capture_state(host)
        except BaseException as exc:
            # No runtime was stopped and no Authority generation exists yet.
            raise RolloutError(phase, exc) from exc
        return previous

    def apply(
        self,
        generation: str,
        bundles: Mapping[str, SecurityBundle],
        *,
        commit: Callable[[], object] | None = None,
        rollback_commit: Callable[[], object] | None = None,
        progress: ProgressCallback | None = None,
        prepared_previous: Mapping[str, HostActivationState] | None = None,
    ) -> RolloutResult:
        _safe_generation(generation)
        if self._topology.security_profile != "sros2":
            raise ValueError("security generation rollout requires the sros2 profile")
        hosts = self._topology.hosts
        host_ids = {host.host_id for host in hosts}
        if set(bundles) != host_ids:
            raise ValueError("one security bundle is required for every host")
        for host in hosts:
            bundle = bundles[host.host_id].validate()
            if bundle.system_id != self._topology.system_id:
                raise ValueError(f"bundle system_id mismatch for {host.host_id}")
            if bundle.host_id != host.host_id or bundle.generation != generation:
                raise ValueError(f"bundle target/generation mismatch for {host.host_id}")

        if prepared_previous is None:
            previous = self._prepare_hosts(progress=progress)
        else:
            host_ids = {host.host_id for host in hosts}
            if set(prepared_previous) != host_ids:
                raise ValueError(
                    "prepared host state must be supplied exactly once for every host"
                )
            previous = dict(prepared_previous)
        stopped: list[ManagedHost] = []
        switched: list[ManagedHost] = []
        phase = "stage"
        try:
            for host in hosts:
                _notify_progress(progress, phase, host.host_id)
                self._operations[host.host_id].stage(host, bundles[host.host_id])
            phase = "stop"
            for host in hosts:
                _notify_progress(progress, phase, host.host_id)
                stopped.append(host)
                self._operations[host.host_id].stop(host)
            phase = "switch"
            for host in hosts:
                _notify_progress(progress, phase, host.host_id)
                switched.append(host)
                self._operations[host.host_id].activate(host, generation)
            phase = "start"
            for host in hosts:
                _notify_progress(progress, phase, host.host_id)
                self._operations[host.host_id].start(host)
            phase = "verify"
            for host in hosts:
                _notify_progress(progress, phase, host.host_id)
                self._operations[host.host_id].verify(host, generation)
            if commit is not None:
                phase = "commit-authority"
                _notify_progress(progress, phase, None)
                commit()
        except BaseException as exc:
            rollback_errors = list(
                self._restore_previous(stopped, switched, previous)
            )
            if phase == "commit-authority" and rollback_commit is not None:
                try:
                    rollback_commit()
                except BaseException as rollback_exc:
                    rollback_errors.append(rollback_exc)
            raise RolloutError(phase, exc, rollback_errors) from exc
        return RolloutResult(
            generation,
            {host_id: state.generation for host_id, state in previous.items()},
        )

    def issue_and_apply(
        self,
        issuer: SecurityGenerationIssuer,
        generation: str,
        *,
        progress: ProgressCallback | None = None,
    ) -> RolloutResult:
        previous = self._prepare_hosts(progress=progress)
        _notify_progress(progress, "issue", None)
        try:
            issued = issuer.issue(self._topology, generation)
            if issued.generation != generation:
                raise ValueError("issuer returned a different security generation")
        except BaseException as exc:
            raise RolloutError("issue", exc) from exc
        return self.apply(
            generation,
            issued.bundles,
            commit=issued.activate_authority,
            rollback_commit=issued.rollback_authority,
            progress=progress,
            prepared_previous=previous,
        )

    def _restore_previous(
        self,
        stopped: Sequence[ManagedHost],
        switched: Sequence[ManagedHost],
        previous: Mapping[str, HostActivationState],
    ) -> tuple[BaseException, ...]:
        return _restore_hosts(
            self._operations,
            stopped=stopped,
            changed=switched,
            previous=previous,
        )


def ssh_sha256_fingerprint(key_bytes: bytes) -> str:
    digest = hashlib.sha256(key_bytes).digest()
    return "SHA256:" + base64.b64encode(digest).decode("ascii").rstrip("=")


def _notify_progress(
    callback: ProgressCallback | None, phase: str, host_id: str | None
) -> None:
    if callback is not None:
        callback(phase, host_id)


def _restore_hosts(
    operations: Mapping[str, HostOperations],
    *,
    stopped: Sequence[ManagedHost],
    changed: Sequence[ManagedHost],
    previous: Mapping[str, HostActivationState],
) -> tuple[BaseException, ...]:
    if not stopped:
        return ()
    errors: list[BaseException] = []
    for host in reversed(stopped):
        try:
            operations[host.host_id].stop(host)
        except BaseException as exc:
            errors.append(exc)
    for host in reversed(changed):
        try:
            operations[host.host_id].rollback(host, previous[host.host_id])
        except BaseException as exc:
            errors.append(exc)
    if errors:
        return tuple(errors)
    for host in stopped:
        try:
            operations[host.host_id].start(host)
        except BaseException as exc:
            errors.append(exc)
    return tuple(errors)


def _net_command(host: ManagedHost) -> PurePosixPath:
    return PurePosixPath(host.bin_dir) / "elesim-net"


def _compose_command(host: ManagedHost) -> tuple[str, ...]:
    compose = PurePosixPath(host.install_root) / "containers/compose.yaml"
    return (
        "docker",
        "compose",
        "-p",
        "elesim-runtime",
        "-f",
        str(compose),
    )


def _robot_service(host: ManagedHost) -> str:
    if host.roles != ("robot",):
        raise ValueError("systemd lifecycle is reserved for the Robot-only host")
    return "elesim-robot.service"


def _lifecycle_command(host: ManagedHost, *, action: str) -> tuple[str, ...]:
    if action not in {"start", "stop"}:
        raise ValueError(f"unsupported lifecycle action: {action!r}")
    if host.lifecycle == "compose":
        if action == "stop":
            return (*_compose_command(host), "down", "--remove-orphans")
        # Installation only writes the Compose context; it deliberately does
        # not build images.  Keep the connection-manager start action
        # equivalent to the generated ``elesim-up`` wrapper.
        return (
            *_compose_command(host),
            "up",
            "-d",
            "--build",
            "--remove-orphans",
        )
    return ("sudo", "-n", "systemctl", action, _robot_service(host))


def _configuration_command(
    host: ManagedHost,
    dds: Mapping[str, Any],
    *,
    sim_id: str = "",
    pilot_id: str = "",
    ui_id: str = "",
    robot_id: str = "",
) -> tuple[str, ...]:
    required = (
        "system_id",
        "domain_id",
        "rmw_implementation",
        "discovery_mode",
        "interface",
        "security_profile",
    )
    missing = [name for name in required if name not in dds]
    if missing:
        raise ValueError("DDS configuration is missing: " + ", ".join(missing))
    arguments: list[str] = [
        str(_net_command(host)),
        "configure",
        "--non-interactive",
        "--dds-system-id",
        str(dds["system_id"]),
        "--dds-domain-id",
        str(dds["domain_id"]),
        "--dds-rmw-implementation",
        str(dds["rmw_implementation"]),
        "--dds-discovery-mode",
        str(dds["discovery_mode"]),
        "--dds-interface",
        str(dds["interface"]),
        "--dds-security-profile",
        str(dds["security_profile"]),
    ]
    peers_raw = dds.get("static_peers", ())
    if not isinstance(peers_raw, Sequence) or isinstance(
        peers_raw, (str, bytes, bytearray)
    ):
        raise ValueError("DDS static_peers must be an array")
    peers = tuple(str(value) for value in peers_raw)
    if peers:
        for peer in peers:
            arguments.extend(("--dds-static-peer", peer))
    else:
        arguments.append("--clear-dds-static-peers")

    security_profile = str(dds["security_profile"])
    if security_profile == "sros2":
        provisioning = str(dds.get("security_provisioning", "external"))
        arguments.extend(("--dds-security-provisioning", provisioning))
        generation = str(dds.get("security_generation", ""))
        bundle = str(dds.get("security_bundle", ""))
        keystore = str(dds.get("keystore", ""))
        enclave = str(dds.get("enclave", ""))
        if generation:
            arguments.extend(("--dds-security-generation", generation))
        if bundle:
            arguments.extend(("--dds-security-bundle", bundle))
        if keystore:
            arguments.extend(("--dds-keystore", keystore))
        if enclave:
            arguments.extend(("--dds-enclave", enclave))
    if sim_id:
        arguments.extend(("--sim-id", sim_id))
    if pilot_id:
        arguments.extend(("--pilot-id", pilot_id))
    if ui_id:
        arguments.extend(("--ui-id", ui_id))
    if robot_id:
        arguments.extend(("--robot-id", robot_id))
    return tuple(arguments)


def _rollback_authority_if_active(
    authority: object, transaction: object, generation: str
) -> object | None:
    active = authority.active()  # type: ignore[attr-defined]
    if active is None or str(active.generation) != generation:
        return None
    return transaction.rollback()  # type: ignore[attr-defined]


def _check_bundle_target(host: ManagedHost, bundle: SecurityBundle) -> None:
    host.validate()
    bundle.validate()
    if bundle.host_id != host.host_id:
        raise ValueError(
            f"security bundle for {bundle.host_id!r} cannot be sent to {host.host_id!r}"
        )


def _safe_identifier(value: str, *, name: str) -> str:
    text = str(value)
    if (
        not text
        or len(text) > 128
        or text in {".", ".."}
        or any(
            character
            not in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._-"
            for character in text
        )
    ):
        raise ValueError(f"{name} is not a safe identifier")
    return text


def _safe_generation(value: str) -> str:
    text = str(value)
    if (
        not text
        or len(text) > 96
        or text[0] not in "abcdefghijklmnopqrstuvwxyz0123456789"
        or any(
            character not in "abcdefghijklmnopqrstuvwxyz0123456789._-"
            for character in text
        )
    ):
        raise ValueError("generation is not a safe lower-case identifier")
    return text


def _safe_relative_path(value: str) -> PurePosixPath:
    if not isinstance(value, str) or not value or "\\" in value or "\x00" in value:
        raise ValueError("security bundle path must be a non-empty POSIX path")
    path = PurePosixPath(value)
    if path.is_absolute() or any(part in {"", ".", ".."} for part in path.parts):
        raise ValueError(f"security bundle path escapes its generation: {value!r}")
    return path


def _safe_remote_root(value: str) -> PurePosixPath:
    if not isinstance(value, str) or "\x00" in value:
        raise ValueError("security_root must be a remote absolute path")
    path = PurePosixPath(value)
    names = [part for part in path.parts if part != "/"]
    if not path.is_absolute() or ".." in path.parts or len(names) < 2:
        raise ValueError("security_root must be a contained absolute path")
    return path


def _sftp_makedirs(sftp: object, path: PurePosixPath) -> None:
    current = PurePosixPath("/")
    for part in path.parts:
        if part == "/":
            continue
        current /= part
        try:
            attributes = sftp.stat(str(current))  # type: ignore[attr-defined]
            if not stat.S_ISDIR(attributes.st_mode):
                raise NotADirectoryError(str(current))
        except OSError:
            sftp.mkdir(str(current), mode=0o700)  # type: ignore[attr-defined]


__all__ = [
    "GenerationRollout",
    "HostActivationState",
    "HostKeyVerificationError",
    "HostOperations",
    "InstalledElesimLifecycle",
    "IssuedSecurityGeneration",
    "LocalHostOperations",
    "MAX_BUNDLE_BYTES",
    "MAX_BUNDLE_FILE_BYTES",
    "MAX_BUNDLE_FILES",
    "ParamikoConnector",
    "ProgressCallback",
    "RemoteCapabilities",
    "RemoteCommandError",
    "RemoteCommandResult",
    "RemoteLifecycle",
    "RolloutError",
    "RolloutResult",
    "SecurityBundle",
    "SecurityGenerationIssuer",
    "SecurityFile",
    "Sros2BundleIssuer",
    "SshAuthenticationError",
    "SshConnectionError",
    "SshConnector",
    "SshHostOperations",
    "SshSession",
    "TopologyRollout",
    "TopologyRolloutResult",
    "ssh_sha256_fingerprint",
]
