"""ROS 2/DDS peer transport without a central application service.

The domain applications use :class:`Envelope` as their in-process command DTO.
On the wire, ``elesim_interfaces/PeerEnvelope`` is a bounded DDS carrier.
Discovery is an application announcement/heartbeat mesh; no participant
forwards traffic for another participant.

All ROS imports are deliberately lazy.  Importing ``elesim_protocol`` therefore
continues to work in release/build tooling that is not running inside a sourced
ROS environment.
"""

from __future__ import annotations

import hashlib
import json
import math
import os
import re
import threading
import time
import uuid
from collections import deque
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any, Callable, Iterator, Mapping, Optional

from .authority import (
    AuthorityError,
    LeaseFence,
    MotionLease,
    MotionLeaseAuthority,
    SimulationSession,
    SimulationSessionAuthority,
)
from .messages import (
    MEDIA_SECURITY_DDS,
    MEDIA_SECURITY_DTLS_SRTP,
    MEDIA_SECURITY_NONE,
    MEDIA_TRANSPORT_DDS,
    PROTOCOL_VERSION,
    EndpointDescriptor,
    Envelope,
    MediaStreamDescriptor,
    ProtocolError,
)
from .payloads import (
    CloseSimulationSessionRequest,
    DiscoverRequest,
    MotionCommandRequest,
    OpenSimulationSessionRequest,
    SelectTargetRequest,
    SimulationSessionGrantedPayload,
    SimulationSessionOpenedPayload,
    SimulationSessionRevokedPayload,
    WebRtcSignalPayload,
    validate_routed_payload,
)
from .peer import (
    PeerAmbiguityError,
    PeerDescriptor,
    PeerDirectory,
    PeerHeartbeat,
    PeerIdentity,
)


_ROS_NAME_COMPONENT = re.compile(r"[^a-zA-Z0-9_]")
_DISCOVERY_PERIOD_S = 1.0
_DESCRIPTOR_PERIOD_S = 2.5
_MAX_PAYLOAD_JSON = 1_048_576
_MAX_TRACE_JSON = 16_384
_MAX_PENDING_INBOUND = 512


class DdsTransportError(RuntimeError):
    """DDS runtime, discovery, serialization, or delivery failed."""


def _bounded_int(value: object, *, name: str, minimum: int, maximum: int) -> int:
    if isinstance(value, bool):
        raise ValueError(f"{name} must be an integer")
    try:
        parsed = int(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{name} must be an integer") from exc
    if parsed < minimum or parsed > maximum:
        raise ValueError(f"{name} must be in {minimum}..{maximum}")
    return parsed


def ros_name_component(value: object, *, fallback: str = "default") -> str:
    """Return a stable ROS-name-safe component with collision-resistant suffix."""

    raw = str(value).strip()
    if not raw:
        raw = str(fallback).strip() or "default"
    normalized = _ROS_NAME_COMPONENT.sub("_", raw).strip("_")
    if not normalized:
        normalized = str(fallback).strip("_") or "default"
    if normalized[0].isdigit():
        normalized = "n_" + normalized
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()[:8]
    return f"{normalized[:48]}_{digest}"


def peer_node_key(endpoint_id: str) -> str:
    return ros_name_component(endpoint_id, fallback="peer")


@dataclass(frozen=True)
class DdsRuntimeSettings:
    """Process-local DDS settings generated by the installer.

    ``trusted-network`` deliberately performs no DDS encryption.  It is for a
    loopback, private LAN, or routed VPN whose membership is controlled outside
    Elesim.  ``sros2`` enables fail-closed DDS Security and requires a keystore
    and enclave.
    """

    system_id: str = "elesim"
    domain_id: int = 0
    rmw_implementation: str = "rmw_cyclonedds_cpp"
    discovery_mode: str = "multicast"
    static_peers: tuple[str, ...] = ()
    network_interface: str = ""
    vendor_config: str = ""
    security_profile: str = "trusted-network"
    keystore: str = ""
    enclave: str = ""
    heartbeat_timeout_s: float = 3.5

    def __post_init__(self) -> None:
        system_id = str(self.system_id).strip()
        if not system_id or len(system_id) > 128:
            raise ValueError("DDS system_id must contain 1..128 characters")
        object.__setattr__(self, "system_id", system_id)
        object.__setattr__(
            self,
            "domain_id",
            _bounded_int(self.domain_id, name="DDS domain_id", minimum=0, maximum=232),
        )
        rmw = str(self.rmw_implementation).strip()
        if not rmw:
            raise ValueError("DDS rmw_implementation is required")
        object.__setattr__(self, "rmw_implementation", rmw)
        discovery = str(self.discovery_mode).strip().lower()
        if discovery not in {"multicast", "static"}:
            raise ValueError("DDS discovery_mode must be multicast or static")
        peers = tuple(str(peer).strip() for peer in self.static_peers if str(peer).strip())
        if discovery == "static" and not peers:
            raise ValueError("static DDS discovery requires at least one peer")
        object.__setattr__(self, "discovery_mode", discovery)
        object.__setattr__(self, "static_peers", peers)
        security = str(self.security_profile).strip().lower()
        if security not in {"trusted-network", "sros2"}:
            raise ValueError(
                "DDS security_profile must be trusted-network or sros2"
            )
        object.__setattr__(self, "security_profile", security)
        keystore = str(self.keystore).strip()
        enclave = str(self.enclave).strip()
        if security == "sros2":
            if not keystore:
                raise ValueError("sros2 security requires a keystore")
            if not enclave or not enclave.startswith("/"):
                raise ValueError("sros2 security requires an absolute enclave name")
        object.__setattr__(self, "keystore", keystore)
        object.__setattr__(self, "enclave", enclave)
        timeout = float(self.heartbeat_timeout_s)
        if not math.isfinite(timeout) or timeout <= 0.0:
            raise ValueError("DDS heartbeat_timeout_s must be positive and finite")
        object.__setattr__(self, "heartbeat_timeout_s", timeout)

    @classmethod
    def from_env(cls, *, endpoint_id: str = "") -> "DdsRuntimeSettings":
        peers = tuple(
            value.strip()
            for value in os.environ.get("ELESIM_DDS_STATIC_PEERS", "").split(",")
            if value.strip()
        )
        security = os.environ.get(
            "ELESIM_DDS_SECURITY_PROFILE",
            "sros2" if os.environ.get("ROS_SECURITY_ENABLE", "").lower() == "true"
            else "trusted-network",
        )
        enclave = os.environ.get("ELESIM_DDS_ENCLAVE", "").strip()
        if security == "sros2" and not enclave:
            base = (
                os.environ.get("ELESIM_DDS_ENCLAVE_BASE", "/elesim").strip()
                or "/elesim"
            )
            if not base.startswith("/"):
                base = "/" + base
            enclave = (
                f"{base.rstrip('/')}/{peer_node_key(endpoint_id or 'peer')}"
            )
        return cls(
            system_id=os.environ.get("ELESIM_SYSTEM_ID", "elesim"),
            domain_id=os.environ.get("ROS_DOMAIN_ID", "0"),
            rmw_implementation=os.environ.get(
                "RMW_IMPLEMENTATION", "rmw_cyclonedds_cpp"
            ),
            discovery_mode=os.environ.get(
                "ELESIM_DDS_DISCOVERY_MODE", "multicast"
            ),
            static_peers=peers,
            network_interface=os.environ.get(
                "ELESIM_DDS_NETWORK_INTERFACE", ""
            ),
            vendor_config=os.environ.get("ELESIM_DDS_VENDOR_CONFIG", ""),
            security_profile=security,
            keystore=os.environ.get("ROS_SECURITY_KEYSTORE", ""),
            enclave=enclave,
            heartbeat_timeout_s=float(
                os.environ.get("ELESIM_DDS_HEARTBEAT_TIMEOUT_S", "3.5")
            ),
        )

    @classmethod
    def from_mapping(
        cls,
        raw: Mapping[str, object],
        *,
        endpoint_id: str = "",
    ) -> "DdsRuntimeSettings":
        """Parse the installer's top-level ``dds`` application section."""

        if not isinstance(raw, Mapping):
            raise ValueError("DDS settings must be an object")
        security = str(raw.get("security_profile", "trusted-network")).strip()
        enclave = str(raw.get("enclave", "")).strip()
        if security == "sros2" and not enclave:
            base = str(raw.get("enclave_base", "/elesim")).strip() or "/elesim"
            if not base.startswith("/"):
                base = "/" + base
            enclave = (
                f"{base.rstrip('/')}/{peer_node_key(endpoint_id or 'peer')}"
            )
        peers_raw = raw.get("static_peers", ())
        if not isinstance(peers_raw, (list, tuple)):
            raise ValueError("DDS static_peers must be a list")
        return cls(
            system_id=str(raw.get("system_id", "elesim")),
            domain_id=raw.get("domain_id", 0),
            rmw_implementation=str(
                raw.get("rmw_implementation", "rmw_cyclonedds_cpp")
            ),
            discovery_mode=str(raw.get("discovery_mode", "multicast")),
            static_peers=tuple(str(value) for value in peers_raw),
            network_interface=str(
                raw.get(
                    "network_interface",
                    raw.get("interface", ""),
                )
            ),
            vendor_config=str(raw.get("vendor_config", "")),
            security_profile=security,
            keystore=str(raw.get("keystore", "")),
            enclave=enclave,
            heartbeat_timeout_s=float(
                raw.get("heartbeat_timeout_s", 3.5)
            ),
        )

    @property
    def namespace(self) -> str:
        # Installer validation restricts system_id to a ROS-safe lowercase
        # component. Keep the human-visible namespace stable across hosts.
        component = _ROS_NAME_COMPONENT.sub("_", self.system_id).strip("_")
        if not component:
            component = "elesim"
        if component[0].isdigit():
            component = "n_" + component
        return f"/{component}/v6"

    def apply_environment(self) -> tuple[str, ...]:
        """Apply process-wide RMW/security settings before importing rclpy."""

        current_rmw = os.environ.get("RMW_IMPLEMENTATION", "").strip()
        if current_rmw and current_rmw != self.rmw_implementation:
            raise DdsTransportError(
                "RMW_IMPLEMENTATION is already set to "
                f"{current_rmw!r}, expected {self.rmw_implementation!r}"
            )
        os.environ["RMW_IMPLEMENTATION"] = self.rmw_implementation
        os.environ["ROS_DOMAIN_ID"] = str(self.domain_id)

        vendor = str(self.vendor_config).strip()
        if vendor:
            resolved = str(Path(vendor).expanduser().resolve())
            if "cyclonedds" in self.rmw_implementation:
                os.environ["CYCLONEDDS_URI"] = (
                    resolved if resolved.startswith("file://") else f"file://{resolved}"
                )
            elif "fastrtps" in self.rmw_implementation or "fastdds" in self.rmw_implementation:
                os.environ["FASTRTPS_DEFAULT_PROFILES_FILE"] = resolved

        ros_args: list[str] = []
        if self.security_profile == "sros2":
            os.environ["ROS_SECURITY_ENABLE"] = "true"
            os.environ["ROS_SECURITY_STRATEGY"] = "Enforce"
            os.environ["ROS_SECURITY_KEYSTORE"] = str(
                Path(self.keystore).expanduser().resolve()
            )
            ros_args.extend(("--ros-args", "--enclave", self.enclave))
        else:
            os.environ.pop("ROS_SECURITY_ENABLE", None)
            os.environ.pop("ROS_SECURITY_STRATEGY", None)
            os.environ.pop("ROS_SECURITY_KEYSTORE", None)
            os.environ.pop("ROS_SECURITY_ENCLAVE_OVERRIDE", None)
        return tuple(ros_args)


@dataclass(frozen=True)
class DiscoveredPeer:
    descriptor: EndpointDescriptor
    identity: PeerIdentity
    node_key: str
    service_prefix: str
    topic_prefix: str


def _float_to_ros_time(message: Any, value: float) -> None:
    seconds = max(0.0, float(value))
    whole = int(seconds)
    message.sec = whole
    message.nanosec = int((seconds - whole) * 1_000_000_000)


def _ros_time_to_float(message: Any) -> float:
    return float(message.sec) + float(message.nanosec) / 1_000_000_000.0


class DdsPeerNode:
    """One DDS participant/node with direct per-peer inbox topics."""

    def __init__(
        self,
        descriptor: EndpointDescriptor,
        *,
        settings: Optional[DdsRuntimeSettings] = None,
        boot_id: str = "",
        clock: Callable[[], float] = time.monotonic,
        wall_clock: Callable[[], float] = time.time,
    ) -> None:
        if not isinstance(descriptor, EndpointDescriptor):
            raise TypeError("DDS peer descriptor must be EndpointDescriptor")
        self.settings = settings or DdsRuntimeSettings.from_env(
            endpoint_id=descriptor.endpoint_id
        )
        self.clock = clock
        self.wall_clock = wall_clock
        self.identity = PeerIdentity(
            descriptor.endpoint_id,
            str(boot_id).strip() or uuid.uuid4().hex,
        )
        self.node_key = peer_node_key(descriptor.endpoint_id)
        self.boot_key = ros_name_component(self.identity.boot_id, fallback="boot")
        self.topic_prefix = (
            f"{self.settings.namespace}/peers/{self.node_key}/{self.boot_key}"
        )
        self.service_prefix = self.topic_prefix
        self.descriptor = replace(descriptor, instance_id=self.identity.boot_id)
        self.directory = PeerDirectory(self.settings.heartbeat_timeout_s)
        self._wire_descriptors: dict[PeerIdentity, DiscoveredPeer] = {}
        self._inbox: deque[tuple[Envelope, PeerIdentity]] = deque()
        self._pending_inbound: deque[
            tuple[Envelope, PeerIdentity, float]
        ] = deque()
        self._inbox_lock = threading.Lock()
        self._publishers: dict[tuple[str, bool], Any] = {}
        self._closed = False
        self._heartbeat_sequence = 0
        self._last_announcement_at: Optional[float] = None
        self._last_heartbeat_at: Optional[float] = None

        ros_args = self.settings.apply_environment()
        try:
            import rclpy
            from elesim_interfaces.msg import (
                EndpointDescriptor as RosEndpointDescriptor,
                EndpointHeartbeat as RosEndpointHeartbeat,
                PeerEnvelope as RosPeerEnvelope,
                PeerRef as RosPeerRef,
                StreamDescriptor as RosStreamDescriptor,
            )
            from rclpy.context import Context
            from rclpy.executors import SingleThreadedExecutor
            from rclpy.qos import (
                DurabilityPolicy,
                HistoryPolicy,
                QoSProfile,
                ReliabilityPolicy,
            )
        except ImportError as exc:
            raise DdsTransportError(
                "ROS 2/DDS runtime is unavailable. Source /opt/ros/humble/setup.bash "
                "and the Elesim interfaces overlay before starting this role."
            ) from exc

        self._rclpy = rclpy
        self._RosPeerRef = RosPeerRef
        self._RosStreamDescriptor = RosStreamDescriptor
        self._RosEndpointDescriptor = RosEndpointDescriptor
        self._RosEndpointHeartbeat = RosEndpointHeartbeat
        self._RosPeerEnvelope = RosPeerEnvelope
        self._context = Context()
        init_args = list(ros_args)
        try:
            self._context.init(args=init_args, domain_id=self.settings.domain_id)
        except TypeError:
            # Older Humble patch releases read ROS_DOMAIN_ID from the environment.
            self._context.init(args=init_args)
        node_name = (
            f"elesim_{self.descriptor.role}_{self.node_key}_{self.boot_key}"
        )[:255]
        self._node = rclpy.create_node(
            node_name,
            context=self._context,
            namespace=self.settings.namespace,
            use_global_arguments=True,
        )
        self._executor = SingleThreadedExecutor(context=self._context)
        self._executor.add_node(self._node)

        discovery_qos = QoSProfile(
            history=HistoryPolicy.KEEP_LAST,
            depth=64,
            reliability=ReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.TRANSIENT_LOCAL,
        )
        heartbeat_qos = QoSProfile(
            history=HistoryPolicy.KEEP_LAST,
            depth=64,
            reliability=ReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.VOLATILE,
        )
        control_qos = QoSProfile(
            history=HistoryPolicy.KEEP_LAST,
            depth=64,
            reliability=ReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.VOLATILE,
        )
        motion_qos = QoSProfile(
            history=HistoryPolicy.KEEP_LAST,
            depth=1,
            reliability=ReliabilityPolicy.BEST_EFFORT,
            durability=DurabilityPolicy.VOLATILE,
        )
        self._control_qos = control_qos
        self._motion_qos = motion_qos
        discovery_topic = f"{self.settings.namespace}/discovery/endpoints"
        heartbeat_topic = f"{self.settings.namespace}/discovery/heartbeats"
        self._descriptor_publisher = self._node.create_publisher(
            RosEndpointDescriptor, discovery_topic, discovery_qos
        )
        self._heartbeat_publisher = self._node.create_publisher(
            RosEndpointHeartbeat, heartbeat_topic, heartbeat_qos
        )
        self._descriptor_subscription = self._node.create_subscription(
            RosEndpointDescriptor,
            discovery_topic,
            self._on_descriptor,
            discovery_qos,
        )
        self._heartbeat_subscription = self._node.create_subscription(
            RosEndpointHeartbeat,
            heartbeat_topic,
            self._on_heartbeat,
            heartbeat_qos,
        )
        self._control_subscription = self._node.create_subscription(
            RosPeerEnvelope,
            f"{self.topic_prefix}/control",
            lambda message: self._on_envelope(message, motion=False),
            control_qos,
        )
        self._motion_subscription = self._node.create_subscription(
            RosPeerEnvelope,
            f"{self.topic_prefix}/motion",
            lambda message: self._on_envelope(message, motion=True),
            motion_qos,
        )
        self.heartbeat(force=True)

    @property
    def registered(self) -> bool:
        return not self._closed

    def transport_ready(self) -> bool:
        return not self._closed and self._context.ok()

    def heartbeat(self, *, force: bool = False) -> None:
        if self._closed:
            return
        now = self.clock()
        if (
            force
            or self._last_announcement_at is None
            or now - self._last_announcement_at >= _DESCRIPTOR_PERIOD_S
        ):
            self._descriptor_publisher.publish(self._descriptor_message())
            self._last_announcement_at = now
        if (
            force
            or self._last_heartbeat_at is None
            or now - self._last_heartbeat_at >= _DISCOVERY_PERIOD_S
        ):
            self._heartbeat_sequence += 1
            heartbeat = self._RosEndpointHeartbeat()
            heartbeat.peer = self._peer_ref_message(self.identity)
            heartbeat.descriptor_revision = 1
            heartbeat.sequence = self._heartbeat_sequence
            self._heartbeat_publisher.publish(heartbeat)
            self._last_heartbeat_at = now
        expired = self.directory.expire(now=now)
        for identity in expired:
            self._wire_descriptors.pop(identity, None)
        self._expire_pending_inbound(now)
        self.spin_once(timeout_s=0.0)

    def spin_once(self, *, timeout_s: float) -> None:
        if self._closed:
            return
        self._executor.spin_once(timeout_sec=max(0.0, float(timeout_s)))

    def discover(
        self,
        *,
        role: str = "",
        capability: str = "",
    ) -> tuple[DiscoveredPeer, ...]:
        now = self.clock()
        descriptors = self.directory.discover(
            now=now,
            role=role,
            capability=capability,
        )
        return tuple(
            self._wire_descriptors[item.identity]
            for item in descriptors
            if item.identity in self._wire_descriptors
            and item.identity != self.identity
        )

    def resolve(self, endpoint_id: str) -> Optional[DiscoveredPeer]:
        descriptor = self.directory.resolve(endpoint_id, now=self.clock())
        if descriptor is None:
            return None
        return self._wire_descriptors.get(descriptor.identity)

    def describe(self, identity: PeerIdentity) -> Optional[DiscoveredPeer]:
        """Return the live descriptor for one exact endpoint incarnation."""

        peer = self._wire_descriptors.get(identity)
        if peer is None:
            return None
        resolved = self.resolve(identity.endpoint_id)
        return peer if resolved is not None and resolved.identity == identity else None

    def publish(self, envelope: Envelope, *, motion: bool = False) -> None:
        if self._closed:
            raise DdsTransportError("DDS peer is closed")
        target = self.resolve(envelope.target_id)
        if target is None:
            raise DdsTransportError(
                f"target peer {envelope.target_id!r} is not active"
            )
        message = self._RosPeerEnvelope()
        message.version = PROTOCOL_VERSION
        message.message_id = envelope.message_id or uuid.uuid4().hex
        message.type = envelope.message_type
        message.source_id = self.identity.endpoint_id
        message.source_boot_id = self.identity.boot_id
        message.target_id = target.identity.endpoint_id
        message.target_boot_id = target.identity.boot_id
        message.seq = int(envelope.seq)
        _float_to_ros_time(message.timestamp, float(envelope.timestamp or self.wall_clock()))
        message.lease_id = str(envelope.lease_id)
        payload_json = json.dumps(
            dict(envelope.payload or {}),
            ensure_ascii=False,
            separators=(",", ":"),
            sort_keys=True,
        )
        trace_json = json.dumps(
            dict(envelope.trace_context or {}),
            ensure_ascii=False,
            separators=(",", ":"),
            sort_keys=True,
        )
        if len(payload_json.encode("utf-8")) > _MAX_PAYLOAD_JSON:
            raise ProtocolError("DDS peer payload exceeds 1 MiB")
        if len(trace_json.encode("utf-8")) > _MAX_TRACE_JSON:
            raise ProtocolError("DDS trace context exceeds 16 KiB")
        message.payload_json = payload_json
        message.trace_json = trace_json
        key = (target.topic_prefix, bool(motion))
        publisher = self._publishers.get(key)
        if publisher is None:
            topic = f"{target.topic_prefix}/{'motion' if motion else 'control'}"
            publisher = self._node.create_publisher(
                self._RosPeerEnvelope,
                topic,
                self._motion_qos if motion else self._control_qos,
            )
            self._publishers[key] = publisher
        publisher.publish(message)

    def receive(self, timeout_ms: int = 0) -> Iterator[tuple[Envelope, PeerIdentity]]:
        self.spin_once(timeout_s=max(0, int(timeout_ms)) / 1000.0)
        while True:
            with self._inbox_lock:
                if not self._inbox:
                    return
                item = self._inbox.popleft()
            yield item

    def inject_local(self, envelope: Envelope, source: Optional[PeerIdentity] = None) -> None:
        with self._inbox_lock:
            self._inbox.append((envelope, source or self.identity))

    def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        try:
            self._executor.remove_node(self._node)
        except Exception:
            pass
        try:
            self._node.destroy_node()
        finally:
            try:
                self._executor.shutdown(timeout_sec=1.0)
            except Exception:
                pass
            if self._context.ok():
                self._context.shutdown()

    def _peer_ref_message(self, identity: PeerIdentity) -> Any:
        message = self._RosPeerRef()
        message.endpoint_id = identity.endpoint_id
        message.boot_id = identity.boot_id
        return message

    def _descriptor_message(self) -> Any:
        message = self._RosEndpointDescriptor()
        message.protocol_major = PROTOCOL_VERSION
        message.peer = self._peer_ref_message(self.identity)
        message.role = self.descriptor.role
        message.capabilities = list(self.descriptor.capabilities)
        message.descriptor_revision = 1
        message.service_prefix = self.service_prefix
        message.topic_prefix = self.topic_prefix
        message.interface_hash = "elesim-v6"
        streams = []
        for name, descriptor in sorted((self.descriptor.streams or {}).items()):
            stream = self._RosStreamDescriptor()
            stream.name = str(name)
            stream.transport = str(descriptor.transport)
            stream.media_kind = str(descriptor.media_kind)
            stream.endpoint = str(descriptor.endpoint)
            stream.message_type = (
                "elesim_interfaces/msg/RgbdFrame"
                if descriptor.media_kind == "rgbd"
                and descriptor.transport == "dds"
                else ""
            )
            stream.qos_profile = (
                "sensor_data_keep_last_1"
                if descriptor.transport == "dds"
                else ""
            )
            streams.append(stream)
        message.streams = streams
        return message

    def _on_descriptor(self, message: Any) -> None:
        try:
            if int(message.protocol_major) != PROTOCOL_VERSION:
                return
            identity = PeerIdentity(
                str(message.peer.endpoint_id),
                str(message.peer.boot_id),
            )
            if identity == self.identity:
                return
            streams: dict[str, MediaStreamDescriptor] = {}
            for stream in message.streams:
                streams[str(stream.name)] = MediaStreamDescriptor(
                    transport=str(stream.transport),
                    media_kind=str(stream.media_kind),
                    endpoint=str(stream.endpoint),
                    security=(
                        MEDIA_SECURITY_DDS
                        if str(stream.transport) == MEDIA_TRANSPORT_DDS
                        and self.settings.security_profile == "sros2"
                        else MEDIA_SECURITY_NONE
                        if str(stream.transport) == MEDIA_TRANSPORT_DDS
                        else MEDIA_SECURITY_DTLS_SRTP
                    ),
                )
            endpoint = EndpointDescriptor(
                endpoint_id=identity.endpoint_id,
                role=str(message.role),
                capabilities=tuple(str(item) for item in message.capabilities),
                streams=streams or None,
                instance_id=identity.boot_id,
            )
            descriptor = PeerDescriptor(
                identity=identity,
                role=endpoint.role,
                capabilities=endpoint.capabilities,
                descriptor_revision=int(message.descriptor_revision),
                service_prefix=str(message.service_prefix),
                topic_prefix=str(message.topic_prefix),
                interface_hash=str(message.interface_hash),
            )
            self.directory.announce(descriptor, now=self.clock())
            self._wire_descriptors[identity] = DiscoveredPeer(
                descriptor=endpoint,
                identity=identity,
                node_key=peer_node_key(identity.endpoint_id),
                service_prefix=descriptor.service_prefix,
                topic_prefix=descriptor.topic_prefix,
            )
            self._release_pending_inbound(identity)
        except (PeerAmbiguityError, ProtocolError, ValueError):
            return

    def _on_heartbeat(self, message: Any) -> None:
        try:
            identity = PeerIdentity(
                str(message.peer.endpoint_id),
                str(message.peer.boot_id),
            )
            if identity == self.identity:
                return
            accepted = self.directory.heartbeat(
                PeerHeartbeat(
                    identity=identity,
                    descriptor_revision=int(message.descriptor_revision),
                    sequence=int(message.sequence),
                ),
                now=self.clock(),
            )
            if accepted:
                self._release_pending_inbound(identity)
        except ValueError:
            return

    def _on_envelope(self, message: Any, *, motion: bool) -> None:
        del motion
        try:
            if int(message.version) != PROTOCOL_VERSION:
                return
            if (
                str(message.target_id) != self.identity.endpoint_id
                or str(message.target_boot_id) != self.identity.boot_id
            ):
                return
            source = PeerIdentity(
                str(message.source_id),
                str(message.source_boot_id),
            )
            payload = json.loads(str(message.payload_json) or "{}")
            trace = json.loads(str(message.trace_json) or "{}")
            if not isinstance(payload, dict) or not isinstance(trace, dict):
                return
            envelope = Envelope(
                message_type=str(message.type),
                source_id=source.endpoint_id,
                target_id=self.identity.endpoint_id,
                payload=payload,
                seq=int(message.seq),
                timestamp=_ros_time_to_float(message.timestamp),
                message_id=str(message.message_id),
                lease_id=str(message.lease_id),
                trace_context={str(key): str(value) for key, value in trace.items()},
                version=int(message.version),
            )
            known = self.directory.resolve(source.endpoint_id, now=self.clock())
        except (json.JSONDecodeError, PeerAmbiguityError, ProtocolError, ValueError):
            return
        if known is None or known.identity != source:
            self._defer_inbound(envelope, source)
            return
        with self._inbox_lock:
            self._inbox.append((envelope, source))

    def _defer_inbound(self, envelope: Envelope, source: PeerIdentity) -> None:
        """Hold startup-racing traffic until the exact source boot is known."""

        with self._inbox_lock:
            if len(self._pending_inbound) >= _MAX_PENDING_INBOUND:
                self._pending_inbound.popleft()
            self._pending_inbound.append((envelope, source, self.clock()))

    def _release_pending_inbound(self, identity: PeerIdentity) -> None:
        try:
            known = self.directory.resolve(identity.endpoint_id, now=self.clock())
        except PeerAmbiguityError:
            return
        if known is None or known.identity != identity:
            return
        cutoff = self.clock() - self.settings.heartbeat_timeout_s
        ready: list[tuple[Envelope, PeerIdentity]] = []
        retained: deque[tuple[Envelope, PeerIdentity, float]] = deque()
        with self._inbox_lock:
            while self._pending_inbound:
                envelope, source, received_at = self._pending_inbound.popleft()
                if received_at < cutoff:
                    continue
                if source == identity:
                    ready.append((envelope, source))
                else:
                    retained.append((envelope, source, received_at))
            self._pending_inbound.extend(retained)
            self._inbox.extend(ready)

    def _expire_pending_inbound(self, now: float) -> None:
        cutoff = float(now) - self.settings.heartbeat_timeout_s
        with self._inbox_lock:
            while (
                self._pending_inbound
                and self._pending_inbound[0][2] < cutoff
            ):
                self._pending_inbound.popleft()


@dataclass(frozen=True)
class _RemoteAuthority:
    resource: PeerIdentity
    lease_id: str
    next_renew_at: float


def _authority_id(epoch: int, token: str) -> str:
    return f"{int(epoch)}:{str(token)}"


def _authority_fence(
    lease_id: str,
    *,
    resource: PeerIdentity,
    owner: PeerIdentity,
    sequence: int,
) -> LeaseFence:
    epoch_raw, separator, token = str(lease_id).partition(":")
    if not separator or not token:
        raise AuthorityError("invalid peer authority token")
    try:
        epoch = int(epoch_raw)
    except ValueError as exc:
        raise AuthorityError("invalid peer authority epoch") from exc
    return LeaseFence(
        resource=resource,
        owner=owner,
        epoch=epoch,
        token=token,
        sequence=int(sequence),
    )


class PeerClient:
    """Application-facing direct peer lifecycle.

    The class intentionally keeps the small ``send/receive/heartbeat`` surface
    used by the deployments.  Unlike the former broker client, discovery is
    local DDS graph state and motion/session authority is evaluated only by the
    resource peer.  No peer relays traffic for another peer.
    """

    def __init__(
        self,
        descriptor: EndpointDescriptor,
        *,
        settings: Optional[DdsRuntimeSettings] = None,
        heartbeat_s: float = 1.0,
        max_pending: int = 512,
        trace_context_provider: Optional[
            Callable[[], Mapping[str, str]]
        ] = None,
        node_factory: Callable[..., DdsPeerNode] = DdsPeerNode,
        turn_credential_provider: Optional[
            Callable[[str, str, float], Any]
        ] = None,
        clock: Callable[[], float] = time.monotonic,
        wall_clock: Callable[[], float] = time.time,
    ) -> None:
        if not isinstance(descriptor, EndpointDescriptor):
            raise TypeError("PeerClient requires an EndpointDescriptor")
        self.clock = clock
        self.wall_clock = wall_clock
        self.heartbeat_s = max(0.1, float(heartbeat_s))
        self.max_pending = max(1, int(max_pending))
        self.trace_context_provider = trace_context_provider
        self.turn_credential_provider = turn_credential_provider
        self.node = node_factory(
            descriptor,
            settings=settings,
            clock=clock,
            wall_clock=wall_clock,
        )
        self.descriptor = self.node.descriptor
        self.seq = 0
        self._closed = False
        self._remote_motion: Optional[_RemoteAuthority] = None
        self._remote_session: Optional[_RemoteAuthority] = None
        self._owned_motion: Optional[MotionLease] = None
        self._owned_session: Optional[SimulationSession] = None
        self._session_ui_turn: Any = None
        self._session_sim_turn: Any = None
        self._local_queue: deque[Envelope] = deque()
        self._motion_authority = (
            MotionLeaseAuthority(
                self.node.identity,
                lease_ttl_s=max(3.5, self.heartbeat_s * 3.5),
            )
            if self.descriptor.role in {"robot", "sim"}
            else None
        )
        self._session_authority = (
            SimulationSessionAuthority(
                self.node.identity,
                lease_ttl_s=max(3.5, self.heartbeat_s * 3.5),
            )
            if self.descriptor.role == "sim"
            else None
        )

    @property
    def registered(self) -> bool:
        return not self._closed and bool(self.node.registered)

    def heartbeat(self, *, force: bool = False) -> None:
        if self._closed:
            return
        self.node.heartbeat(force=force)
        now = self.clock()
        self._renew_remote_authorities(now=now)
        self._expire_owned_authorities(now=now)
        self._detect_lost_remote_authorities(now=now)

    def send(
        self,
        message_type: str,
        *,
        target_id: str = "server",
        payload: Optional[dict[str, object]] = None,
        lease_id: str = "",
        trace_context: Optional[Mapping[str, str]] = None,
    ) -> Envelope:
        if self._closed:
            raise DdsTransportError("DDS peer client is closed")
        body = dict(payload or {})
        validate_routed_payload(message_type, body)
        if message_type == "discover":
            return self._discover(body, trace_context=trace_context)
        if message_type == "select_target":
            target_id = SelectTargetRequest.from_payload(body).target_id
        elif message_type == "release_target":
            target_id = (
                ""
                if self._remote_motion is None
                else self._remote_motion.resource.endpoint_id
            )
            lease_id = (
                ""
                if self._remote_motion is None
                else self._remote_motion.lease_id
            )
        elif message_type == "open_simulation_session":
            target_id = OpenSimulationSessionRequest.from_payload(
                body
            ).sim_id
        elif message_type == "close_simulation_session":
            target_id = (
                ""
                if self._remote_session is None
                else self._remote_session.resource.endpoint_id
            )
            lease_id = (
                lease_id
                or (
                    ""
                    if self._remote_session is None
                    else self._remote_session.lease_id
                )
            )
        elif message_type == "simulation_status" and target_id == "server":
            return self._publish_simulation_status(
                body,
                lease_id=lease_id,
                trace_context=trace_context,
            )
        if not target_id or target_id == "server":
            raise DdsTransportError(
                f"{message_type} requires a directly discovered target peer"
            )
        envelope = self._envelope(
            message_type,
            target_id=target_id,
            payload=body,
            lease_id=lease_id,
            trace_context=trace_context,
        )
        motion = False
        if message_type == "motion_command":
            command = MotionCommandRequest.from_payload(body).command
            motion = command != "estop"
        self.node.publish(envelope, motion=motion)
        return envelope

    def receive(self, timeout_ms: int = 0) -> Iterator[Envelope]:
        while self._local_queue:
            yield self._local_queue.popleft()
        for envelope, source in self.node.receive(timeout_ms=timeout_ms):
            try:
                routed = self._route_inbound(envelope, source)
            except (AuthorityError, ProtocolError, ValueError) as exc:
                self._send_error(envelope, source, str(exc) or "invalid request")
                continue
            for item in routed:
                yield item
        while self._local_queue:
            yield self._local_queue.popleft()

    def close(self) -> None:
        if self._closed:
            return
        now = self.clock()
        if self._motion_authority is not None:
            lease = self._motion_authority.revoke(now=now, reason="peer_closed")
            if lease is not None:
                self._notify_motion_revoked(lease, "peer_closed")
        if self._session_authority is not None:
            session = self._session_authority.revoke(
                now=now,
                reason="peer_closed",
            )
            if session is not None:
                self._notify_session_revoked(session, "peer_closed")
        self._closed = True
        self.node.close()

    def _trace_context(
        self,
        explicit: Optional[Mapping[str, str]],
    ) -> dict[str, str]:
        if explicit is not None:
            return {str(key): str(value) for key, value in explicit.items()}
        if self.trace_context_provider is None:
            return {}
        return {
            str(key): str(value)
            for key, value in self.trace_context_provider().items()
        }

    def _envelope(
        self,
        message_type: str,
        *,
        target_id: str,
        payload: Mapping[str, object],
        lease_id: str = "",
        trace_context: Optional[Mapping[str, str]] = None,
        message_id: str = "",
    ) -> Envelope:
        self.seq += 1
        return Envelope(
            message_type=str(message_type),
            source_id=self.descriptor.endpoint_id,
            target_id=str(target_id),
            payload=dict(payload),
            seq=self.seq,
            timestamp=self.wall_clock(),
            message_id=str(message_id) or uuid.uuid4().hex,
            lease_id=str(lease_id),
            trace_context=self._trace_context(trace_context),
        )

    def _local_envelope(
        self,
        message_type: str,
        *,
        payload: Mapping[str, object],
        lease_id: str = "",
        source_id: Optional[str] = None,
        trace_context: Optional[Mapping[str, str]] = None,
    ) -> Envelope:
        envelope = self._envelope(
            message_type,
            target_id=self.descriptor.endpoint_id,
            payload=payload,
            lease_id=lease_id,
            trace_context=trace_context,
        )
        if source_id is not None:
            envelope = replace(envelope, source_id=str(source_id))
        self._local_queue.append(envelope)
        return envelope

    def _discover(
        self,
        payload: Mapping[str, object],
        *,
        trace_context: Optional[Mapping[str, str]],
    ) -> Envelope:
        request = DiscoverRequest.from_payload(payload)
        peers = self.node.discover(
            role=request.role,
            capability=request.capability,
        )
        return self._local_envelope(
            "endpoint_list",
            payload={
                "endpoints": [
                    peer.descriptor.to_dict()
                    for peer in sorted(
                        peers,
                        key=lambda value: (
                            value.descriptor.role,
                            value.descriptor.endpoint_id,
                        ),
                    )
                ]
            },
            trace_context=trace_context,
        )

    def _publish_simulation_status(
        self,
        payload: Mapping[str, object],
        *,
        lease_id: str,
        trace_context: Optional[Mapping[str, str]],
    ) -> Envelope:
        recipients: list[tuple[PeerIdentity, str]] = []
        if self._owned_motion is not None:
            recipients.append(
                (
                    self._owned_motion.pilot,
                    _authority_id(
                        self._owned_motion.epoch,
                        self._owned_motion.token,
                    ),
                )
            )
        if self._owned_session is not None:
            recipients.append(
                (
                    self._owned_session.ui,
                    _authority_id(
                        self._owned_session.epoch,
                        self._owned_session.token,
                    ),
                )
            )
        first: Optional[Envelope] = None
        seen: set[PeerIdentity] = set()
        for recipient, authority_id in recipients:
            if recipient in seen or self.node.describe(recipient) is None:
                continue
            seen.add(recipient)
            envelope = self._envelope(
                "simulation_status",
                target_id=recipient.endpoint_id,
                payload=payload,
                lease_id=lease_id or authority_id,
                trace_context=trace_context,
            )
            self.node.publish(envelope)
            if first is None:
                first = envelope
        if first is not None:
            return first
        return self._envelope(
            "simulation_status",
            target_id=self.descriptor.endpoint_id,
            payload=payload,
            lease_id=lease_id,
            trace_context=trace_context,
        )

    def _route_inbound(
        self,
        envelope: Envelope,
        source: PeerIdentity,
    ) -> tuple[Envelope, ...]:
        message_type = envelope.message_type
        if message_type == "select_target":
            self._handle_select_target(envelope, source)
            return ()
        if message_type == "renew_target":
            self._handle_renew_target(envelope, source)
            return ()
        if message_type == "release_target":
            self._handle_release_target(envelope, source)
            return ()
        if message_type == "open_simulation_session":
            self._handle_open_session(envelope, source)
            return ()
        if message_type == "renew_simulation_session":
            self._handle_renew_session(envelope, source)
            return ()
        if message_type == "close_simulation_session":
            self._handle_close_session(envelope, source)
            return ()
        if message_type == "motion_command":
            return self._authorize_motion(envelope, source)
        if message_type in {"simulation_command", "webrtc_signal"}:
            return self._authorize_simulation(envelope, source)
        if message_type == "target_selected":
            self._observe_target_selected(envelope, source)
        elif message_type in {"target_released", "target_lost"}:
            self._remote_motion = None
        elif message_type == "simulation_session_opened":
            self._observe_session_opened(envelope, source)
        elif message_type == "simulation_session_revoked":
            self._remote_session = None
        return (envelope,)

    def _require_source_role(
        self,
        source: PeerIdentity,
        roles: set[str],
    ) -> DiscoveredPeer:
        peer = self.node.describe(source)
        if peer is None:
            raise AuthorityError("request source is no longer a live DDS peer")
        if peer.descriptor.role not in roles:
            expected = ", ".join(sorted(roles))
            raise AuthorityError(f"request requires source role: {expected}")
        return peer

    def _request_fence(self, request: Envelope, source: PeerIdentity) -> LeaseFence:
        return _authority_fence(
            request.lease_id,
            resource=self.node.identity,
            owner=source,
            sequence=request.seq,
        )

    def _handle_select_target(
        self,
        request: Envelope,
        source: PeerIdentity,
    ) -> None:
        self._require_source_role(source, {"pilot"})
        if self._motion_authority is None:
            raise AuthorityError("this peer does not own a motion target")
        parsed = SelectTargetRequest.from_payload(request.payload or {})
        if parsed.target_id != self.descriptor.endpoint_id:
            raise AuthorityError("select_target addressed the wrong target")
        now = self.clock()
        active = self._motion_authority.active(now=now)
        if active is not None and active.pilot == source:
            fence = active.fence(request.seq)
            decision = self._motion_authority.renew(
                source,
                fence,
                request.message_id,
                now=now,
            )
        else:
            decision = self._motion_authority.acquire(
                source,
                request.message_id,
                now=now,
            )
        if not decision.accepted or decision.lease is None:
            raise AuthorityError(f"motion target unavailable: {decision.reason}")
        lease = decision.lease
        lease_id = _authority_id(lease.epoch, lease.token)
        changed = (
            self._owned_motion is None
            or self._owned_motion.epoch != lease.epoch
            or self._owned_motion.pilot != lease.pilot
        )
        self._owned_motion = lease
        if changed:
            self._local_envelope(
                "lease_granted",
                payload={"pilot_id": source.endpoint_id},
                lease_id=lease_id,
                source_id=self.descriptor.endpoint_id,
                trace_context=request.trace_context,
            )
        response = self._envelope(
            "target_selected",
            target_id=source.endpoint_id,
            payload={
                "target_id": self.descriptor.endpoint_id,
                "lease_id": lease_id,
            },
            lease_id=lease_id,
            trace_context=request.trace_context,
        )
        self.node.publish(response)

    def _handle_renew_target(
        self,
        request: Envelope,
        source: PeerIdentity,
    ) -> None:
        self._require_source_role(source, {"pilot"})
        if self._motion_authority is None:
            raise AuthorityError("this peer does not own a motion target")
        fence = self._request_fence(request, source)
        decision = self._motion_authority.renew(
            source,
            fence,
            request.message_id,
            now=self.clock(),
        )
        if not decision.accepted or decision.lease is None:
            raise AuthorityError(f"motion lease renewal rejected: {decision.reason}")
        self._owned_motion = decision.lease

    def _handle_release_target(
        self,
        request: Envelope,
        source: PeerIdentity,
    ) -> None:
        self._require_source_role(source, {"pilot"})
        if self._motion_authority is None:
            raise AuthorityError("this peer does not own a motion target")
        fence = self._request_fence(request, source)
        decision = self._motion_authority.release(
            source,
            fence,
            request.message_id,
            now=self.clock(),
        )
        if not decision.accepted or decision.lease is None:
            raise AuthorityError(f"motion lease release rejected: {decision.reason}")
        self._owned_motion = None
        self._notify_motion_revoked(decision.lease, "released")

    def _authorize_motion(
        self,
        request: Envelope,
        source: PeerIdentity,
    ) -> tuple[Envelope, ...]:
        self._require_source_role(source, {"pilot"})
        if self._motion_authority is None:
            raise AuthorityError("this peer does not accept motion commands")
        command = MotionCommandRequest.from_payload(request.payload or {}).command
        if command == "estop":
            return (request,)
        fence = self._request_fence(request, source)
        decision = self._motion_authority.accept_command(
            fence,
            now=self.clock(),
        )
        if not decision.accepted:
            raise AuthorityError(f"motion command rejected: {decision.reason}")
        self._owned_motion = self._motion_authority.active(now=self.clock())
        return (request,)

    def _handle_open_session(
        self,
        request: Envelope,
        source: PeerIdentity,
    ) -> None:
        self._require_source_role(source, {"ui"})
        if self._session_authority is None:
            raise AuthorityError("this peer does not own simulation sessions")
        parsed = OpenSimulationSessionRequest.from_payload(request.payload or {})
        if parsed.sim_id != self.descriptor.endpoint_id:
            raise AuthorityError("simulation session addressed the wrong sim")
        decision = self._session_authority.open(
            source,
            parsed.streams,
            parsed.request_id,
            now=self.clock(),
        )
        if not decision.accepted or decision.session is None:
            raise AuthorityError(f"simulation session unavailable: {decision.reason}")
        session = decision.session
        changed = (
            self._owned_session is None
            or self._owned_session.epoch != session.epoch
            or self._owned_session.ui != session.ui
        )
        self._owned_session = session
        self._ensure_turn_credentials(session, force=changed)
        self._publish_session_grant(
            session,
            request_id=parsed.request_id,
            trace_context=request.trace_context,
            local_changed=changed,
        )

    def _handle_renew_session(
        self,
        request: Envelope,
        source: PeerIdentity,
    ) -> None:
        self._require_source_role(source, {"ui"})
        if self._session_authority is None:
            raise AuthorityError("this peer does not own simulation sessions")
        fence = self._request_fence(request, source)
        decision = self._session_authority.renew(
            source,
            fence,
            request.message_id,
            now=self.clock(),
        )
        if not decision.accepted or decision.session is None:
            raise AuthorityError(
                f"simulation session renewal rejected: {decision.reason}"
            )
        self._owned_session = decision.session
        refreshed = self._ensure_turn_credentials(decision.session)
        if refreshed:
            self._publish_session_grant(
                decision.session,
                request_id=request.message_id,
                trace_context=request.trace_context,
                local_changed=True,
            )

    def _handle_close_session(
        self,
        request: Envelope,
        source: PeerIdentity,
    ) -> None:
        self._require_source_role(source, {"ui"})
        if self._session_authority is None:
            raise AuthorityError("this peer does not own simulation sessions")
        parsed = CloseSimulationSessionRequest.from_payload(request.payload or {})
        if parsed.session_id != request.lease_id:
            raise AuthorityError("simulation close session token mismatch")
        fence = self._request_fence(request, source)
        decision = self._session_authority.close(
            source,
            fence,
            parsed.request_id,
            now=self.clock(),
        )
        if not decision.accepted or decision.session is None:
            raise AuthorityError(f"simulation close rejected: {decision.reason}")
        self._owned_session = None
        self._notify_session_revoked(decision.session, "closed")

    def _authorize_simulation(
        self,
        request: Envelope,
        source: PeerIdentity,
    ) -> tuple[Envelope, ...]:
        # Answers flow sim -> UI and are validated by the UI session.
        if self.descriptor.role != "sim":
            return (request,)
        self._require_source_role(source, {"ui"})
        if self._session_authority is None:
            raise AuthorityError("this peer does not accept simulation commands")
        channel = request.message_type
        if request.message_type == "webrtc_signal":
            signal = WebRtcSignalPayload.from_payload(request.payload or {})
            if signal.signal != "offer":
                raise AuthorityError("sim accepts only WebRTC offers from UI peers")
            channel = f"webrtc:{signal.stream}"
        fence = self._request_fence(request, source)
        decision = self._session_authority.accept(
            fence,
            channel,
            now=self.clock(),
        )
        if not decision.accepted:
            raise AuthorityError(
                f"simulation request rejected: {decision.reason}"
            )
        self._owned_session = self._session_authority.active(now=self.clock())
        return (request,)

    def _observe_target_selected(
        self,
        response: Envelope,
        source: PeerIdentity,
    ) -> None:
        self._require_source_role(source, {"robot", "sim"})
        payload = dict(response.payload or {})
        target_id = str(payload.get("target_id", ""))
        lease_id = str(payload.get("lease_id", response.lease_id))
        if target_id != source.endpoint_id or not lease_id:
            raise AuthorityError("invalid target_selected response")
        _authority_fence(
            lease_id,
            resource=source,
            owner=self.node.identity,
            sequence=response.seq,
        )
        self._remote_motion = _RemoteAuthority(
            source,
            lease_id,
            self.clock() + self.heartbeat_s,
        )

    def _observe_session_opened(
        self,
        response: Envelope,
        source: PeerIdentity,
    ) -> None:
        self._require_source_role(source, {"sim"})
        opened = SimulationSessionOpenedPayload.from_payload(response.payload or {})
        if (
            opened.sim_id != source.endpoint_id
            or opened.session_id != response.lease_id
        ):
            raise AuthorityError("invalid simulation_session_opened response")
        _authority_fence(
            opened.session_id,
            resource=source,
            owner=self.node.identity,
            sequence=response.seq,
        )
        self._remote_session = _RemoteAuthority(
            source,
            opened.session_id,
            self.clock() + self.heartbeat_s,
        )

    def _renew_remote_authorities(self, *, now: float) -> None:
        motion = self._remote_motion
        if motion is not None and now >= motion.next_renew_at:
            if self.node.describe(motion.resource) is None:
                self._lose_remote_motion("target_peer_lost")
            else:
                envelope = self._envelope(
                    "renew_target",
                    target_id=motion.resource.endpoint_id,
                    payload={},
                    lease_id=motion.lease_id,
                )
                try:
                    self.node.publish(envelope)
                except DdsTransportError:
                    self._lose_remote_motion("target_peer_lost")
                else:
                    self._remote_motion = replace(
                        motion,
                        next_renew_at=now + self.heartbeat_s,
                    )
        session = self._remote_session
        if session is not None and now >= session.next_renew_at:
            if self.node.describe(session.resource) is None:
                self._lose_remote_session("sim_peer_lost")
            else:
                envelope = self._envelope(
                    "renew_simulation_session",
                    target_id=session.resource.endpoint_id,
                    payload={},
                    lease_id=session.lease_id,
                )
                try:
                    self.node.publish(envelope)
                except DdsTransportError:
                    self._lose_remote_session("sim_peer_lost")
                else:
                    self._remote_session = replace(
                        session,
                        next_renew_at=now + self.heartbeat_s,
                    )

    def _detect_lost_remote_authorities(self, *, now: float) -> None:
        del now
        motion = self._remote_motion
        if motion is not None and self.node.describe(motion.resource) is None:
            self._lose_remote_motion("target_peer_lost")
        session = self._remote_session
        if session is not None and self.node.describe(session.resource) is None:
            self._lose_remote_session("sim_peer_lost")

    def _expire_owned_authorities(self, *, now: float) -> None:
        if self._motion_authority is not None and self._owned_motion is not None:
            previous = self._owned_motion
            active = self._motion_authority.active(now=now)
            self._owned_motion = active
            if active is None:
                self._notify_motion_revoked(previous, "lease_expired")
        if self._session_authority is not None and self._owned_session is not None:
            previous = self._owned_session
            active = self._session_authority.active(now=now)
            self._owned_session = active
            if active is None:
                self._notify_session_revoked(previous, "session_expired")

    def _lose_remote_motion(self, reason: str) -> None:
        remote = self._remote_motion
        self._remote_motion = None
        if remote is None:
            return
        self._local_envelope(
            "target_lost",
            payload={
                "target_id": remote.resource.endpoint_id,
                "reason": str(reason),
            },
            lease_id=remote.lease_id,
            source_id=remote.resource.endpoint_id,
        )

    def _lose_remote_session(self, reason: str) -> None:
        remote = self._remote_session
        self._remote_session = None
        if remote is None:
            return
        payload = SimulationSessionRevokedPayload(
            session_id=remote.lease_id,
            sim_id=remote.resource.endpoint_id,
            reason=str(reason),
        )
        self._local_envelope(
            "simulation_session_revoked",
            payload=payload.to_payload(),
            lease_id=remote.lease_id,
            source_id=remote.resource.endpoint_id,
        )

    def _notify_motion_revoked(self, lease: MotionLease, reason: str) -> None:
        lease_id = _authority_id(lease.epoch, lease.token)
        self._local_envelope(
            "lease_revoked",
            payload={"reason": str(reason)},
            lease_id=lease_id,
            source_id=self.descriptor.endpoint_id,
        )
        if self.node.describe(lease.pilot) is not None:
            response = self._envelope(
                "target_released",
                target_id=lease.pilot.endpoint_id,
                payload={
                    "target_id": self.descriptor.endpoint_id,
                    "reason": str(reason),
                },
                lease_id=lease_id,
            )
            self.node.publish(response)

    def _notify_session_revoked(
        self,
        session: SimulationSession,
        reason: str,
    ) -> None:
        session_id = _authority_id(session.epoch, session.token)
        payload = SimulationSessionRevokedPayload(
            session_id=session_id,
            sim_id=self.descriptor.endpoint_id,
            reason=str(reason),
        )
        self._local_envelope(
            "simulation_session_revoked",
            payload=payload.to_payload(),
            lease_id=session_id,
            source_id=self.descriptor.endpoint_id,
        )
        if self.node.describe(session.ui) is not None:
            response = self._envelope(
                "simulation_session_revoked",
                target_id=session.ui.endpoint_id,
                payload=payload.to_payload(),
                lease_id=session_id,
            )
            self.node.publish(response)
        self._session_ui_turn = None
        self._session_sim_turn = None

    def _ensure_turn_credentials(
        self,
        session: SimulationSession,
        *,
        force: bool = False,
    ) -> bool:
        provider = self.turn_credential_provider
        if provider is None:
            changed = force and (
                self._session_ui_turn is not None
                or self._session_sim_turn is not None
            )
            self._session_ui_turn = None
            self._session_sim_turn = None
            return changed
        now = self.wall_clock()
        expires_at = min(
            float(getattr(self._session_ui_turn, "expires_at", 0.0)),
            float(getattr(self._session_sim_turn, "expires_at", 0.0)),
        )
        if not force and expires_at - now > 120.0:
            return False
        session_id = _authority_id(session.epoch, session.token)
        self._session_ui_turn = provider(
            session.ui.endpoint_id,
            session_id,
            now,
        )
        self._session_sim_turn = provider(
            self.descriptor.endpoint_id,
            session_id,
            now,
        )
        return True

    def _publish_session_grant(
        self,
        session: SimulationSession,
        *,
        request_id: str,
        trace_context: Optional[Mapping[str, str]],
        local_changed: bool,
    ) -> None:
        session_id = _authority_id(session.epoch, session.token)
        if local_changed:
            local = SimulationSessionGrantedPayload(
                request_id=request_id,
                session_id=session_id,
                sim_id=self.descriptor.endpoint_id,
                ui_id=session.ui.endpoint_id,
                streams=session.streams,
                turn=self._session_sim_turn,
            )
            self._local_envelope(
                "simulation_session_granted",
                payload=local.to_payload(),
                lease_id=session_id,
                source_id=self.descriptor.endpoint_id,
                trace_context=trace_context,
            )
        opened = SimulationSessionOpenedPayload(
            request_id=request_id,
            session_id=session_id,
            sim_id=self.descriptor.endpoint_id,
            streams=session.streams,
            turn=self._session_ui_turn,
        )
        response = self._envelope(
            "simulation_session_opened",
            target_id=session.ui.endpoint_id,
            payload=opened.to_payload(),
            lease_id=session_id,
            trace_context=trace_context,
        )
        self.node.publish(response)

    def _send_error(
        self,
        request: Envelope,
        source: PeerIdentity,
        reason: str,
    ) -> None:
        if self.node.describe(source) is None:
            return
        response = self._envelope(
            "error",
            target_id=source.endpoint_id,
            payload={
                "reply_to": request.message_id,
                "reason": str(reason)[:1024],
            },
            trace_context=request.trace_context,
        )
        try:
            self.node.publish(response)
        except DdsTransportError:
            return


__all__ = [
    "DdsPeerNode",
    "DdsRuntimeSettings",
    "DdsTransportError",
    "DiscoveredPeer",
    "PeerClient",
    "peer_node_key",
    "ros_name_component",
]
